### PR TITLE
Add Brainbread2 (draft)

### PR DESCRIPTION
**Pull request by AshlyneS**
Adds BrainBread2 dedicated server.

| System      | Version | Status |
| ----------- | ----------- | ----------- |
**Linux** | Ubuntu (20.04.4) | Working
**Windows** | Windows 10 | Working (with reduced console output)

**To Do:**
- [ ] Add workshop support
- [ ] Correct monitor output
- [ ] Configuration polishing and sorting

### CODE REVIEW

**Comment by IceOfWraith** [comment]
Are you ready for someone to test this and release as Linux only? Or do you plan to submit some type of feature request for the stderr issue?

**Comment by AshlyneS** [comment]
> Are you ready for someone to test this and release as Linux only? Or do you plan to submit some type of feature request for the stderr issue?

You can go ahead and test linux but the configuration manifest still needs some sorting and polishing. I also have yet to get it to output the correct monitor values or workshop. 

I fixed the windows STDIO issue but with the drawback of reduced console output.

**Comment by IceOfWraith** [comment]
I'll wait until you have it polished to avoid double testing. That's great you got it running though!

**Comment by IceOfWraith** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
