### PR TITLE
Add Half-Life

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by sxon-xo** [comment]
Hey Greelan - I would like to know if an option could be added to the GUI for selecting a third-party mod. The -game parameter is hardcoded in the .kvp as "valve" and cannot be changed unless manually adjusted. Could an option be added so that it can be manually specified if desired, setting valve as the default for Half-Life? I was able to get a server up and running with a mod with the pre-25th beta but had to adjust the .kvp manually to remove the valve and place it with the option I wanted. If it doesn't make a lot of sense to you to add, don't stress it, as doing it manually is, of course, possible.

**Comment by Greelan** [comment]
Sure, easy.

Could you also test how `App.IgnoreSTDOUTAfterRCON=True` works in the kvp? You will need to add it. It helps suppress repeated RCON command output but I want to see whether it also suppresses other logging that it shouldn't, including importantly user joins and leaves.

**Comment by sxon-xo** [comment]
> Sure, easy.
> 
> Could you also test how `App.IgnoreSTDOUTAfterRCON=True` works in the kvp? You will need to add it. It helps suppress repeated RCON command output but I want to see whether it also suppresses other logging that it shouldn't, including importantly user joins and leaves.

When making that change I lose all console output once the server starts. (No joins/leaves/disconnects - no in-game chat).

**Comment by Greelan** [comment]
Yeah, as I suspected it is a hacky "solution" to the repeated console output. If anything it probably would be better the other way - suppress RCON output rather than STDOUT. 

The proper solution ofc is for AMP just to filter any output that is actually a repeat line, rather than just blindly ignoring one channel or another.

**Comment by sxon-xo** [comment]
> Yeah, as I suspected it is a hacky "solution" to the repeated console output. If anything it probably would be better the other way - suppress RCON output rather than STDOUT.
> 
> The proper solution ofc is for AMP just to filter any output that is actually a repeat line, rather than just blindly ignoring one channel or another.

Just edited my post above to include some logs. I am not noticing any duplicated output at this time with the option set to False. I was trying to play around with the userjoin and userleave regex as its currently blank in the .kvp - I was able to get it to track correctly but it kept jumbling the console with weird chars inserted in the line of the join - It did not seem to effect anything but was just annoying me and after a few tries I threw my hands up.

**Comment by Greelan** [comment]
Run an RCON command

**Comment by Greelan** [comment]
> > Yeah, as I suspected it is a hacky "solution" to the repeated console output. If anything it probably would be better the other way - suppress RCON output rather than STDOUT.
> > The proper solution ofc is for AMP just to filter any output that is actually a repeat line, rather than just blindly ignoring one channel or another.
> 
> Just edited my post above to include some logs. I am not noticing any duplicated output at this time with the option set to False. I was trying to play around with the userjoin and userleave regex as its currently blank in the .kvp - I was able to get it to track correctly but it kept jumbling the console with weird chars inserted in the line of the join - It did not seem to effect anything but was just annoying me and after a few tries I threw my hands up.

What are the log lines? Can't recall if someone ever gave them to me or whether it wasn't workable?

**Comment by sxon-xo** [comment]
> > > Yeah, as I suspected it is a hacky "solution" to the repeated console output. If anything it probably would be better the other way - suppress RCON output rather than STDOUT.
> > > The proper solution ofc is for AMP just to filter any output that is actually a repeat line, rather than just blindly ignoring one channel or another.
> > 
> > 
> > Just edited my post above to include some logs. I am not noticing any duplicated output at this time with the option set to False. I was trying to play around with the userjoin and userleave regex as its currently blank in the .kvp - I was able to get it to track correctly but it kept jumbling the console with weird chars inserted in the line of the join - It did not seem to effect anything but was just annoying me and after a few tries I threw my hands up.
> 
> What are the log lines? Can't recall if someone ever gave them to me or whether it wasn't workable?

Join

`L 12/11/2023 - 20:15:07: "Test<1><STEAM_0:1:REDACTED><>" connected, address "REDACTED:27005"
L 12/11/2023 - 20:15:07: "Test<1><STEAM_0:1:REDACTED><>" STEAM USERID validated
L 12/11/2023 - 20:15:08: "Test<1><STEAM_0:1:16486321><1>" entered the game`

Leave

`L 12/11/2023 - 20:19:57: "Test<1><STEAM_0:1:REDACTED><1>" disconnected
Dropped Test from server
Reason: Client sent 'drop'

**Comment by sxon-xo** [comment]
> You sure you reverted the kvp?

Positive. Just triple checked - made sure the instance was stopped.

image

**Review by IceOfWraith — APPROVED** [review]

**Review by IceOfWraith — DISMISSED** [review]

**Review by IceOfWraith — DISMISSED** [review]

**Comment by Greelan** [comment]
Can't add this yet until the issue with the UDP logger breaking RCON is fixed

**Comment by IceOfWraith** [comment]
Of course. Just didn't want it sitting waiting for me. Does the RCON input and output both break?

**Comment by Greelan** [comment]
Yeah, AMP can't connect

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
