### PR TITLE
Update longvinter.kvp

### PR DESCRIPTION
**Pull request by xLeviNx**
Just support multihome (IP choice) for multiple instances of servers

### CODE REVIEW

**Comment by Greelan** [comment]
I don't think this is the right approach to this. ApplicationIPBinding is not otherwise used by the template so it isn't necessary to use it for this purpose, particularly as this approach will require GenericModule.kvp to be edited anyway. And changing ApplicationIPBinding doesn't change the displayed endpoint. 

I will add a setting that allows the MultiHome IP to be added via the UI, like a number of other templates.

**Comment by IceOfWraith** [comment]
Or perhaps, we use this as a cause to push an issue request to ask Mike to make it editable in generic?

**Comment by Greelan** [comment]
Useful addition, but again won't make any practical difference in this case. 

Better yet, there should be a dropdown of available interface IPs, like in the official modules. Plus an empty field to avoid the flag being used at all (needed eg for Ark).

**Comment by Greelan** [comment]
For Longvinter, the devs have changed how the default Game.ini is handled and also some of the contents. So will add those as well

**Comment by Greelan** [comment]
See https://github.com/CubeCoders/AMPTemplates/pull/246

**Comment by xLeviNx** [comment]
Closed ; refer to #246

**Pull request closed without merging**
