### PR TITLE
Valheim - Changed update soruce for BepInEx

### PR DESCRIPTION
**Pull request by gkuba**
Changed the BepInEx update source from the github to fetchURL from thunderstore.io
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

### CODE REVIEW

**Comment by gkuba** [comment]
Tested on Linux to be working.

**Comment by gOOvER** [comment]
GitHub never worked with Valheim, because the libs are missing in the GitHub Release ;)

**Comment by IceOfWraith** [comment]
Yeah, the issue is the Thunderstorm version doesn't seem to work on Windows. If nobody else has a solution, I say we make the update stage Linux only and put a note in the description for now.

**Comment by gkuba** [comment]
See thats weird its not working on a windows AMP instance because I used that version on my client and it works. Is it extracting the files from the BepInExPack_Valheim folder?

**Review by IceOfWraith — CHANGES_REQUESTED** [review]
I see the problem with Windows. Gotta be careful with copy/paste! ;)

`"/C move Valheim\\896660\\BepInExPack_Valheim Valheim\\896660\\UndeadLegacyStable && xcopy /E /Y /I Valheim\\896660\\BepInExPack_Valheim\\* Valheim\\896660\\ && rmdir /Q /S Valheim\\896660\\BepInExPack_Valheim",`

**Comment by gkuba** [comment]
Fixed that real quick. Thanks, sorry I haven't had a ton of time to work on this more.

**Comment by IceOfWraith** [comment]
Try this one instead. :)
`"/C xcopy /E /Y /I Valheim\\896660\\BepInExPack_Valheim\\* Valheim\\896660 && rmdir /Q /S Valheim\\896660\\BepInExPack_Valheim"`

**Comment by gkuba** [comment]
No you are right. Sorry I didn't look at it close enough. I was on my phone at the airport with my kid sending him back to his mother. Its been a long bunch of stressful days. Should be really fixed this time.

**Review by IceOfWraith — APPROVED** [review]
Good work! This will make quite a few people happy.

**Pull request merged**
