### PR TITLE
Update Valheim and ValheimPlus

### PR DESCRIPTION
**Pull request by IceOfWraith**
This adds the release stream option to allow for "default_old" that was recently added. This also enable crossplay functionality.

### CODE REVIEW

**Comment by IceOfWraith** [comment]
This can be tested from my dev branch using `IceOfWraith/AMPTemplates:dev`.

**Comment by Greelan** [comment]
The changes look functional to me, but query whether it is desirable for crossplay to be enabled by default?

This might be another case where getting IsFlagArgument to be capable of being defaulted to False would be useful. The new FlagValue does not appear to work.

**Comment by IceOfWraith** [comment]
Done.

**Comment by Greelan** [comment]
And that actually works? My recollection is that AMP can’t handle the empty false value and it still shows as true

**Comment by IceOfWraith** [comment]
Yeah it defaults to a blank value. I think that was solved a while back with allowing null values.

**Comment by IceOfWraith** [comment]
Is there anything left you'd like to see before approving?

**Review by Greelan — APPROVED** [review]

**Pull request merged**
