### PR TITLE
Add Skyrim Together Reborn

### PR DESCRIPTION
**Pull request by Greelan**
Following on from the great work in https://github.com/CubeCoders/AMPTemplates/pull/314, I've updated the template to:

- add a server download stage
- add stages to create relevant directories and files
- add Linux support
- update and streamline settings

~Leaving in draft at the moment due to a bug in AMP that modifies the download URL when it is saved, causing it not to work.~ Bug now addressed in 2.4.6.4 development branch.

### CODE REVIEW

**Comment by Greelan** [comment]
Related issue: https://github.com/CubeCoders/AMP/issues/921

**Comment by Greelan** [comment]
Requires 2.6.4.4 development branch

**Review by IceOfWraith — DISMISSED** [review]
This one was a beast to test. Apparently you have to download a mod launcher, the mod + other dependency, then beat the first mission in the game. Then you're able to connect. It did work though. It showed me connected and everything fine.

**Comment by Greelan** [comment]
So user join/leave worked? Can you share the log lines?

Thanks for going through the effort with this. I didn't realise it was so difficult!

**Comment by IceOfWraith** [comment]
Yeah I'll reset it up. It did work for tracking join/leave.

**Comment by IceOfWraith** [comment]
```[02:39:08] [info] Connection received 824dc2de
[02:39:08] [info] New player 'Ice' [824dc2de] connected with 10 mods
	: Skyrim.esm, Update.esm, Dawnguard.esm, HearthFires.esm, Dragonborn.esm, ccBGSSSE001-Fish.esm, ccQDRSSE001-SurvivalMode.esl, ccBGSSSE037-Curios.esl, ccBGSSSE025-AdvDSGS.esm, SkyrimTogether.esp
[02:39:44] [info] Connection ended 824dc2de - 'Ice' disconnected```

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
