### PR TITLE
Add No One Survived

### PR DESCRIPTION
**Pull request by Greelan**
Adds No One Survived dedicated server.

Notes:
- All Game.ini settings added.
- Requires Wine 8 on Linux.

### CODE REVIEW

**Comment by gkuba** [comment]
Is this ready for testing?

**Comment by Greelan** [comment]
Should be. Haven't done a final proofread yet, but I guess that's what testing is for :)

It can be installed from my dev branch

**Comment by Greelan** [comment]
One thing I am particularly interested in is whether saves work as expected. Just starting and stopping the server doesn't generate a save file, but maybe it needs a client to connect before it does?

**Comment by gkuba** [comment]
I'll check. I did notice one copy pasta error let me get the line.  262 is the same as 246. I think you meant it to be "Sets the zombie strength"

`    {
        "DisplayName":"Running Corpses Proportion",
        "Category":"NOS Gameplay Settings",
        "Description":"Sets the proportion of running corpses",
        "Keywords":"zombie,corpse,running,percentage,runzombiepercent",
        "FieldName":"RunZombiePercent",
        "InputType":"number",
        "MinValue":"0",
        "MaxValue":"1",
        "IsFlagArgument":false,
        "ParamFieldName":"GameSettings.RunZombiePercent",
        "IncludeInCommandLine":false,
        "DefaultValue":"0.5",
        "Placeholder":"0.5",
        "EnumValues":{}
    },
    {
        "DisplayName":"Zombie Strength",
        "Category":"NOS Gameplay Settings",
        "Description":"Sets the proportion of running corpses",
        "Keywords":"zombie,strength,zombiestreng",
        "FieldName":"ZombieStreng",
        "InputType":"number",
        "MinValue":"0",
        "MaxValue":"3",
        "IsFlagArgument":false,
        "ParamFieldName":"GameSettings.ZombieStreng",
        "IncludeInCommandLine":false,
        "DefaultValue":"1",
        "Placeholder":"1",
        "EnumValues":{}
    },`

**Comment by gkuba** [comment]
Here is the in game screenshot of a dedicated server. 
image

**Comment by Greelan** [comment]
Log lines for user joins/leaves/chats would be awesome too

**Comment by gkuba** [comment]
It does save when players log out which is good. Chat doesn't get logged to the console unfortunately. Join messages show names but disconnects done. 

Join.
```
[2023.04.08-06.31.40:677][489]LogNet: Join succeeded: Katala Swiftwind
```

Leave
```
[2023.04.08-06.35.39:717][584]LogNet: UChannel::ReceivedSequencedBunch: Bunch.bClose == true. ChIndex == 0. Calling ConditionalCleanUp.
[2023.04.08-06.35.39:718][584]LogNet: UChannel::CleanUp: ChIndex == 0. Closing connection. [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 10.13.37.1:47208, Name: IpConnection_2147478989, Driver: GameNetDriver IpNetDriver_2147482424, IsServer: YES, PC: HDCK_Player_Controller_C_2147478985, Owner: HDCK_Player_Controller_C_2147478985, UniqueId: STEAM:UNKNOWN [0x1100001056B6B94]
[2023.04.08-06.35.39:718][584]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 10.13.37.1:47208, Name: IpConnection_2147478989, Driver: GameNetDriver IpNetDriver_2147482424, IsServer: YES, PC: HDCK_Player_Controller_C_2147478985, Owner: HDCK_Player_Controller_C_2147478985, UniqueId: STEAM:UNKNOWN [0x1100001056B6B94], Channels: 91, Time: 2023.04.08-06.35.39
[2023.04.08-06.35.39:718][584]LogNet: UNetConnection::SendCloseReason:
[2023.04.08-06.35.39:718][584]LogNet: - Result=ControlChannelClose, ErrorContext="ControlChannelClose"
[2023.04.08-06.35.39:718][584]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 10.13.37.1:47208, Name: IpConnection_2147478989, Driver: GameNetDriver IpNetDriver_2147482424, IsServer: YES, PC: HDCK_Player_Controller_C_2147478985, Owner: HDCK_Player_Controller_C_2147478985, UniqueId: STEAM:UNKNOWN [0x1100001056B6B94]
24:35:45
[2023.04.08-06.35.39:775][585]LogBlueprintUserMessages: [HDCK_GameMode_C_2147482425] save character[2023.04.08-06.35.45:961][732]LogBlueprintUserMessages: [HDCK_GameMode_C_2147482425] SaveGame
```

**Comment by gkuba** [comment]
So as of right now no way to track players online from what I can see.

**Comment by Greelan** [comment]
Nothing else logged on join that could link the two (leaving AMP's bugs with tracking things like sessionid aside, ofc)?

**Comment by gkuba** [comment]
Actually the `[2023.04.08-06.39.36:307][636]LogNet: Login request: ?Name=Katala Swiftwind userId: STEAM:UNKNOWN [0x1100001056B6B94] platform: STEAM` the hex in [ ] corresponds to the logoff of the same format. 

```
[2023.04.08-06.39.36:242][634]LogNet: NotifyAcceptingConnection accepted from: 10.13.37.1:58950
[2023.04.08-06.39.36:242][634]LogHandshake: SendConnectChallenge. Timestamp: 503.880551, Cookie: 073026028157146038136115106114059235036147089037011238136136
[2023.04.08-06.39.36:243][634]LogNet: NotifyAcceptingConnection accepted from: 10.13.37.1:58950
[2023.04.08-06.39.36:243][634]LogHandshake: SendChallengeAck. InCookie: 073026028157146038136115106114059235036147089037011238136136
[2023.04.08-06.39.36:243][634]LogNet: Server accepting post-challenge connection from: 10.13.37.1:58950
[2023.04.08-06.39.36:243][634]LogNet: IpConnection_2147477039 setting maximum channels to: 32767
[2023.04.08-06.39.36:244][634]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2023.04.08-06.39.36:244][634]LogNet: NotifyAcceptedConnection: Name: HDCKMap, TimeStamp: 04/08/23 06:39:36, [UNetConnection] RemoteAddr: 10.13.37.1:58950, Name: IpConnection_2147477039, Driver: GameNetDriver IpNetDriver_2147482424, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2023.04.08-06.39.36:244][634]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 10.13.37.1:58950, Name: IpConnection_2147477039, Driver: GameNetDriver IpNetDriver_2147482424, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2023.04.08-06.39.36:275][635]LogNet: NotifyAcceptingChannel Control 0 server World /Game/BattleRoyaleStarterKit/Maps/BattleRoyale_Map_a/HDCKMap.HDCKMap: Accepted
[2023.04.08-06.39.36:275][635]LogNet: Remote platform little endian=1
[2023.04.08-06.39.36:275][635]LogNet: This platform little endian=1
[2023.04.08-06.39.36:307][636]LogNet: Login request: ?Name=Katala Swiftwind userId: STEAM:UNKNOWN [0x1100001056B6B94] platform: STEAM
[2023.04.08-06.39.36:310][636]LogNet: Client netspeed is 100000
24:39:40
[2023.04.08-06.39.40:548][761]LogNet: Join request: /Game/BattleRoyaleStarterKit/Maps/BattleRoyale_Map_a/HDCKMap?Name=Katala Swiftwind?SplitscreenCount=1
[2023.04.08-06.39.40:560][761]LogActorComponent: RegisterComponentWithWorld: (/Game/BattleRoyaleStarterKit/Maps/BattleRoyale_Map_a/HDCKMap.HDCKMap:PersistentLevel.HDCK_CharacterBP_C_2147477018.ACFInteraction) Already registered. Aborting.
[2023.04.08-06.39.40:560][761]LogNet: Join succeeded: Katala Swiftwind
```

**Comment by gkuba** [comment]
Other than those small things it runs like a dream on Linux. I can test on a windows box maybe here soon.

**Comment by Greelan** [comment]
Any idea what `Zombies Respawn` in your screenshot above is about. Seems to be ZombieNum in the settings file.

I also can't see in your screenshot any equivalent for the NumOfZombieSpawn setting from the file.

**Comment by gkuba** [comment]
Those two are not in the dedicated side.

**Comment by Greelan** [comment]
So you are saying the setting is repeated? Zombie Wave Multiplier (AttackZombieNum) and Zombie Respawn (ZombieNum)?

Confusing.

**Comment by gkuba** [comment]
Looking at it again on my server and in game. 
AttackZombieNum=2 - This is Zombie Wave Multiplier
ZombieNum=2 - This Zombie Respawn

Like you said Confusing but yes. I think that is right.

**Comment by Greelan** [comment]
Cool. But what does Zombie Respawn mean? The Steam forum post says something like "amount of lost generation on the map", which makes no sense to me.

**Comment by gkuba** [comment]
I'm not 100% sure myself. I thought it was something to the effect of. You killed all 6 zombies in this area now since the multiplier is 2 then 12 will respawn in that area. Next time will be 24 etc until you hit the cap of zombies per player.

**Comment by Greelan** [comment]
No problem, I will make the other changes in the meantime.

**Comment by gkuba** [comment]
The hardest part right now is the translation / language barrier on the explanations of even how to set up the server officially.

**Comment by Greelan** [comment]
Not sure I follow that comment?

**Comment by gkuba** [comment]
Sorry, like I said tired.... 

The game is from what I can tell an Asian company, and they had a hard time explaining how to set up the dedicated server, no explanation of the settings etc. It ls most likely a language barrier or translation issues. Even some of the in game text is in another language.

**Comment by IceOfWraith** [comment]
Did a desktop review and everything seems in order. Unless you find anything else through testing it should be good to merge.

**Comment by Greelan** [comment]
I'm making a bunch of changes with GKuba's great feedback.

The wiki for setting up the server is pretty average (so much out of sync with the game itself) but I've got to give these devs credit - they actually install all the required config files right off the bat

**Comment by Greelan** [comment]
The regex now uses `sessionid`, but of course that is still not working in AMP

**Comment by gkuba** [comment]
Just glad to help. We were about the same place and I finally had time to jump in. 

I'll check the latest version now and see how it is.

**Comment by gkuba** [comment]
SO far everything looks great it picked up my user logged in and dropped me from the list when I logged off. Getting a buddy on to test that with multiple people but Great Job!! Greelan 

Thanks for helping with this one!

**Comment by Greelan** [comment]
Just need to figure what `NumOfZombieSpawn` means. It's in the ServerSetting section of serversettings.xml so maybe that means it show in-game in another menu?

**Comment by gkuba** [comment]
That is number of zombies per player its in the peer to peer settings. its probably set to 50 by default.

**Comment by Greelan** [comment]
Thanks. Actually it was ZombieNum that you were going investigate further

**Comment by gkuba** [comment]
I would word it as "Zombie Respawn Multiplier" until we get more info. I'm still trying to figure out what exactly it really is.

**Comment by gkuba** [comment]
That wording sounds much better. I've had that template up since your last push, and it's running fine still.

**Comment by Greelan** [comment]
I joined the NOS discord and did a search of the setting - this is the best I could glean from the various comments. Lots of people are confused by it; even the mod was a bit vague about what it meant.

**Comment by gkuba** [comment]
Yeah, that is the best I could gleam with my testing as well.

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
