### PR TITLE
Add Open World

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by jakub961241** [comment]
Hello, it's not working. Tested
image

**Comment by jakub961241** [comment]
working please add.


Thank you

**Comment by jakub961241** [comment]
image
image
image

**Comment by IceOfWraith** [comment]
Configs like this make me very thankful Mike added the option to have a separate beautified update file. Lol

**Comment by IceOfWraith** [comment]
I don't own the game so can't test connectivity, but it did launch normally and shutdown properly based on the log. Everything checks out if you want to update the URLs.

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
