### PR TITLE
Pavlov VR: Fix docker support

### PR DESCRIPTION
**Pull request by Greelan**
All along it was AMP...

Also updates ports, tweaks settings

### CODE REVIEW

**Comment by gOOvER** [comment]
still `bEnabled` not in config. its for visibility of the server in serverlist

**Comment by IceOfWraith** [comment]
> still `bEnabled` not in config. its for visibility of the server in serverlist

Where are you seeing this? It's been in the config all along.

**Comment by IceOfWraith** [comment]
I realized you're stating that the setting isn't exposed in the UI. This game only lets you join from the in-game server browser AFAIK. There's no direct connect option. So exposing that would just confuse people and make them unable to join. It's in the ini file as true if someone wanted to change it though.

**Review by IceOfWraith — APPROVED** [review]
Awesome job figuring this one out. This is the most bizarre one yet.

**Pull request merged**
