### PR TITLE
Necesse Game Support Draft

### PR DESCRIPTION
**Pull request by Dragoon209**
Note that the config file download path in the update stage would need to be converted to a new download location.

### CODE REVIEW

**Comment by IceOfWraith** [comment]
So far it looks good on Windows. I'm having an issue on Linux when I try to start it though. It binds to IP `127.0.1.1` so I can't join. Do you know a way to specify the IP?

**Comment by Dragoon209** [comment]
> So far it looks good on Windows. I'm having an issue on Linux when I try to start it though. It binds to IP `127.0.1.1` so I can't join. Do you know a way to specify the IP?

There doesn't appear to be a way to specify the IP it binds to via the game server config.  However, I do not have an issue joining my test server, and I am seeing the same bound IP on the console during startup.

_[2022-08-28 19:57:23] Launched game with arguments: -nogui -localdir -seed -guide y -world world
[2022-08-28 19:57:23] Loading dedicated server on version 0.21.24.
[2022-08-28 19:57:24] Started lan socket at port 55169
[2022-08-28 19:57:24] Started server using port 15002 with 21 slots on world "world" with password "TestPass", game version 0.21.24.
[2022-08-28 19:57:24] Found 0 saved players.
[2022-08-28 19:57:24] Address: 127.0.1.1:15002
[2022-08-28 19:57:24] Type help for list of commands.
---truncated---
[2022-08-28 20:00:40] Creating new player: 76561197963562141
[2022-08-28 20:00:41] Loading map for player: AUTH:76561197963562141
[2022-08-28 20:00:41] Client "76561197963562141" with address **ClientAddress**:52074 is connecting with version 0.21.24.
[2022-08-28 20:01:15] Player 76561197963562141 ("ThisIslandEarth") disconnected with message: Quit_

In my case, my server is running Linux reachable by domain name, and reverse proxy configured.

**Comment by IceOfWraith** [comment]
Hmm... Is the reverse proxy or game client on the same machine as the server by chance? I just updated and launched and can't connect. I redid my network today to clean it up so I'll try again.

**Comment by Dragoon209** [comment]
The Linux server had its reverse proxy set up by the AMP installation, so it does reside on the game server.  It is a separate machine than what is running the game client.  The server is only reachable over the Internet.  Hopefully that helps!

**Comment by IceOfWraith** [comment]
I'm going to chalk it up to poor game design. Lol I tried a few tricks and nothing seemed to work. I'm on LAN but my Windows test server connected right up. 

Get the update stage change to `https://github.com/CubeCoders/AMPTemplates/raw/main/necesseserverconfig.cfg` and I'll give approval and merge this one. Thanks for a good submission!

**Comment by Dragoon209** [comment]
Change made, and I believe I have pushed appropriately, as I can see the change recorded under this pull request.  Please let me know if I did something wrong.  Thanks!

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
