### PR TITLE
Add Arma Reforger

### PR DESCRIPTION
**Pull request by JetF0x**

### CODE REVIEW

**Comment by Greelan** [comment]
Isn't the name of this game Arma **Reforger**? Lol

**Comment by JetF0x** [comment]
> Isn't the name of this game Arma **Reforger**? Lol

fixed lol

**Comment by IceOfWraith** [comment]
You still have one spot in the config manifest with "Reforged" too. :)

**Comment by JetF0x** [comment]
Ready to deploy, waiting for BE fixes to implement battleye.

**Comment by Greelan** [comment]
Has this actually been fully tested? On a quick look, seems some issues with command line args - eg the -profile arg should need / after {{$FullBaseDir}} and the serverfps argument is set once via the command line args and a second, different way via the manifest? Also normally non-used ports should be zeroed out although the new ports system might now fix that for you.

**Comment by JetF0x** [comment]
> Has this actually been fully tested? On a quick look, seems some issues with command line args - eg the -profile arg should need / after {{$FullBaseDir}} and the serverfps argument is set once via the command line args and a second, different way via the manifest? Also normally non-used ports should be zeroed out although the new ports system might now fix that for you.

profile arg didnt need a / after as {{$FullBaseDir}} inserts one already after it, i'll take a triple peek here at setfps in a moment.

**Comment by JetF0x** [comment]
> Has this actually been fully tested? On a quick look, seems some issues with command line args - eg the -profile arg should need / after {{$FullBaseDir}} and the serverfps argument is set once via the command line args and a second, different way via the manifest? Also normally non-used ports should be zeroed out although the new ports system might now fix that for you.

Yeah serverfps is pulled from reforgerconfig.json into the kvp.

**Comment by Greelan** [comment]
Can I see the support tab for an instance after you are started the server?

**Comment by JetF0x** [comment]
image

**Comment by Greelan** [comment]
Looks like Mike has fixed the first issue

But see what I mean that it also adds `-serverfps "75"` as a FormattedArg?

**Comment by JetF0x** [comment]
Ahh now I see what you're talkin about for serverfps

**Comment by Greelan** [comment]
> Looks like Mike has fixed the first issue

But interestingly on another template I have, it doesn’t add the / . The only difference is that your value is in quotes

**Comment by JetF0x** [comment]
> 

I put mine in quotes just because of windows directory might have a space in it sometimes, and armas a **** unless its in quotes..

**Comment by Greelan** [comment]
Just tried my template with quotes, no difference. Weird

**Comment by IceOfWraith** [comment]
Regarding the / in {{$FullBaseDir}} what I believe is when used in the command line or env vars it has a slash, when used in update stages it does not. I'm really not certain why.

**Comment by Greelan** [comment]
I see why. His App.BaseDirectory includes the trailing slash

**Comment by Greelan** [comment]
@JetF0x I have gone through this template in detail and have a bunch of changes/updates. Are you happy if I commit them directly to your PR/fork?

**Comment by JetF0x** [comment]
SureOn Jul 6, 2022 10:26 PM, Greelan ***@***.***> wrote:
@JetF0x I have gone through this template in detail and have a bunch of changes/updates. Are you happy if I commit them directly to your PR/fork?

**Comment by Greelan** [comment]
Is there actually chat on Arma Reforger that appears in the console? If not all my tweaks to the chat regex to avoid server messages being repeated as chat messages are redundant, and the chat regex can just be made `^$`

**Comment by Greelan** [comment]
@JetF0x the BOM issue with the JSON writing has been fixed in 2.3.4.2.

I'm keen then to get this merged. Did you have any comments? In particular, any feedback on the chat query above?

**Comment by JetF0x** [comment]
> Is there actually chat on Arma Reforger that appears in the console? If not all my tweaks to the chat regex to avoid server messages being repeated as chat messages are redundant, and the chat regex can just be made `^$`

I don't recall if there was, I haven't been running a server due to the BOM issue.....

**Comment by Greelan** [comment]
Would be great if you could check again at some point and revert

**Comment by Greelan** [comment]
Bump @JetF0x

**Comment by IceOfWraith** [comment]
Apparently I accidentally clicked ready for review last night. Lol

**Review by IceOfWraith — DISMISSED** [review]
I don't own the game, so I have only reviewed basic functionality. It seems to work as intended up to the point of showing in the Steam server browser. Great work (again)!

**Pull request merged**
