### PR TITLE
Update Empyrion Config Manifest

### PR DESCRIPTION
**Pull request by IceOfWraith**
Added the new Stranded at Nemesis scenario and clarified menu tab names.

### CODE REVIEW

**Review by Greelan — APPROVED** [review]
I hate the new Category name (even "Empyrion Server Settings" would be better), but that is stylistic only.

**Comment by IceOfWraith** [comment]
I needed a balance between length vs visibility. I hate how the current templates are so hard to tell what settings are for the game vs AMP.

**Comment by Greelan** [comment]
"Empyrion Settings" then?

**Comment by IceOfWraith** [comment]
"Empyrion Settings" and "Empyrion Game" seems strange to me. Lol

**Comment by Greelan** [comment]
Didn't focus on the other category. "Empyrion Server" and "Empyrion Game" then. But I really don't care lol

**Comment by IceOfWraith** [comment]
I don't care either. Just trying to improve the layout with what we have to work with. So feedback is definitely welcome.

**Pull request merged**
