### PR TITLE
Add Ground Branch

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by CostcoFanboy** [comment]
Amazing game! +1

**Comment by Greelan** [comment]
> Amazing game! +1

If you'd like to assist with testing the template, please do. You can add it by including my dev branch in your AMP repos: Greelan/AMPTemplates:dev

I particularly need log lines for when users join, leave and chat

**Comment by CostcoFanboy** [comment]
> > Amazing game! +1
> 
> If you'd like to assist with testing the template, please do. You can add it by including my dev branch in your AMP repos: Greelan/AMPTemplates:dev
> 
> I particularly need log lines for when users join, leave and chat

GroundBranch servers are a tad hard to populate. This is me alone in a server if this helps:

```
[2023.06.20-23.58.48:300][195]LogSockets: SteamSockets: Now tracking socket 104002788 for addr 76561198026837263:7778, has parent? 1
[2023.06.20-23.58.48:300][195]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2023.06.20-23.58.48:300][195]LogNet: NotifyAcceptedConnection: Name: 747, TimeStamp: 06/20/23 23:58:48, [UNetConnection] RemoteAddr: 76561198026837263:7778, Name: SteamSocketsNetConnection_2147482056, Driver: GameNetDriver SteamSocketsNetDriver_2147482430, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2023.06.20-23.58.48:300][195]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 76561198026837263:7778, Name: SteamSocketsNetConnection_2147482056, Driver: GameNetDriver SteamSocketsNetDriver_2147482430, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2023.06.20-23.58.48:300][195]LogNet: SteamSockets: New connection (104002788) over listening socket accepted 76561198026837263:7778
[2023.06.20-23.58.49:149][220]LogNet: SteamSockets: Connectionless handshake complete
[2023.06.20-23.58.49:214][222]LogNet: NotifyAcceptingChannel Control 0 server World /Game/GroundBranch/Maps/747/747.747: Accepted
[2023.06.20-23.58.49:214][222]LogNet: Remote platform little endian=1
[2023.06.20-23.58.49:214][222]LogNet: This platform little endian=1
[2023.06.20-23.58.49:280][224]LogNet: Login request: ?Name=NoName userId: Steam:UNKNOWN [0x110000103F7CD0F] platform: Steam
[2023.06.20-23.58.56:216][436]LogNet: Client netspeed is 100000
[2023.06.20-23.58.56:216][436]LogNet: Join request: /Game/GBCore/Maps/ServerDefaultMap?Name=NoName?SplitscreenCount=1
[2023.06.20-23.58.56:217][436]LogNet: Join succeeded: Operator-YJC-48
[2023.06.20-23.59.45:452][933]LogGameMode: [ReadyRoomChat] Operator-YJC-48 : test
[2023.06.20-23.59.46:474][964]LogGameMode: [ReadyRoomChat] Operator-YJC-48 : test
[2023.06.20-23.59.48:079][ 13]LogGameMode: [ReadyRoomChat] Operator-YJC-48 : lol
```

Rollover in next logfile:
```
[00:00:00] [Logger Info]          : Rollover from previous log file: AMP_Logs/AMPLOG 2023-06-20 23-30-10.log
[2023.06.21-00.00.46:259][783]LogGameMode: [ReadyRoomChat] Poutine Man : test after name change
[2023.06.21-00.00.49:962][895]LogTemp: Warning: --intelretrieval:OnRoundStageSet() - new round stage PreRoundWait
[2023.06.21-00.00.49:964][895]LogGBSky: Warning: [DedicatedServer] BP_GBSkyActor_0::OnRep_CycleStartTime(): called, CycleStartTime=1532
[2023.06.21-00.00.54:954][ 47]LogTemp: Warning: --intelretrieval:OnRoundStageSet() - new round stage InProgress
[2023.06.21-00.01.48:364][675]LogGameMode: [GlobalChat] Poutine Man : test death
[2023.06.21-00.01.53:946][845]LogTemp: Warning: --intelretrieval:OnRoundStageSet() - new round stage PostRoundWait
[2023.06.21-00.01.58:951][996]LogGBPlayerState: Warning: AGBPlayerState::SyncPlayerScores() : Could not find scores defined for player Poutine Man.
[2023.06.21-00.01.58:952][996]LogTemp: Warning: --intelretrieval:OnRoundStageSet() - new round stage WaitingForReady
[2023.06.21-00.01.58:952][996]LogTemp: Warning: ----picking laptop 5 (BP_Laptop_747Passenger_03) out of 110 possible
[2023.06.21-00.01.58:957][996]LogGBSky: Warning: [DedicatedServer] BP_GBSkyActor_0::OnRep_CycleStartTime(): called, CycleStartTime=0
[2023.06.21-00.02.06:958][240]LogZK: Warning: UZKVote::VoteCommand(): The vote 'yes' is not known or not allowed
[2023.06.21-00.02.08:045][273]LogZK: Warning: UZKVote::VoteCommand(): The vote 'yes' is not known or not allowed
[2023.06.21-00.02.08:605][290]LogZK: Warning: UZKVote::VoteCommand(): The vote 'no' is not known or not allowed
[2023.06.21-00.02.56:010][726]LogZK: Warning: UZKVote::VoteCommand(): The vote 'yes' is not known or not allowed
[2023.06.21-00.03.08:328][101]LogZK: Warning: UZKVote::VoteCommand(): The vote 'yes' is not known or not allowed
[2023.06.21-00.03.33:729][870]LogNet: UChannel::CleanUp: ChIndex == 0. Closing connection. [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 76561198026837263:7778, Name: SteamSocketsNetConnection_2147482056, Driver: GameNetDriver SteamSocketsNetDriver_2147482430, IsServer: YES, PC: BP_PlayerController_C_2147482052, Owner: BP_PlayerController_C_2147482052, UniqueId: Steam:UNKNOWN [0x110000103F7CD0F]
```

The only red flag I saw is that It's unable to capture the UUID of Steam referring to the player, this may be rather important for bans or external reports. I'm not sure if this is an issue in other games, I have no experience with this.

**Comment by CostcoFanboy** [comment]
I just realized I completely disconnected and took the groundbranch branch over dev. Is this an issue?

**Comment by IceOfWraith** [comment]
Greelan, once you get the regex it looks good.

**Comment by Greelan** [comment]
> I just realized I completely brainfarted and took the groundbranch branch reflexively over dev despite you telling me to test dev. Is this an issue?
> 
> 
> 
> groundbranch branch seems more recent.

Thanks. Shouldn't be an issue. The template files should be identical.

**Comment by Greelan** [comment]
Unfortunately the log lines aren't great. The best I think is using the steam ID, but that won't show a name in AMP's UI and will not address chat. It is what it is, I guess.

**Comment by Greelan** [comment]
@CostcoFanboy BTW, did you test this on Linux or Windows? Curious to know where the server saves are on Linux, coz I couldn't find them. Would be useful to know the same on Windows.

**Comment by CostcoFanboy** [comment]
@Greelan I found them in `/home/amp/.ampdata/instances/GroundBranch01/AMP_Logs/*`. Unsure about Windows, I tend not to touch Windows for anything except gaming.

**Comment by Greelan** [comment]
> @Greelan I found them in `/home/amp/.ampdata/instances/GroundBranch01/AMP_Logs/*`. Unsure about Windows, I tend not to touch Windows for anything except gaming.
> 
> ```
> /home/amp/.ampdata/instances/GroundBranch01/AMP_Logs
> ├── AMPLOG 2023-06-20 23-30-05.log
> ├── AMPLOG 2023-06-20 23-30-10.log
> ├── AMPLOG 2023-06-21 00-00-00.log
> └── AMPLOG 2023-06-22 00-00-00.log
> 
> 1 directory, 4 files
> ```

I meant the actual server saves (of the world or whatever, dunno what GB produces), not the AMP logs

**Comment by CostcoFanboy** [comment]
> > @Greelan I found them in `/home/amp/.ampdata/instances/GroundBranch01/AMP_Logs/*`. Unsure about Windows, I tend not to touch Windows for anything except gaming.
> > ```
> > /home/amp/.ampdata/instances/GroundBranch01/AMP_Logs
> > ├── AMPLOG 2023-06-20 23-30-05.log
> > ├── AMPLOG 2023-06-20 23-30-10.log
> > ├── AMPLOG 2023-06-21 00-00-00.log
> > └── AMPLOG 2023-06-22 00-00-00.log
> > 
> > 1 directory, 4 files
> > ```
> 
> I meant the actual server saves (of the world or whatever, dunno what GB produces), not the AMP logs

If it's the original logs you meant, then they should be here:
```
/home/amp/.ampdata/instances/GroundBranch01/ground-branch/476400/GroundBranch/Saved/Logs
├── GroundBranch-backup-2023.06.21-23.43.48.log
├── GroundBranch-backup-2023.06.21-23.43.54.log
└── GroundBranch.log

1 directory, 3 files
```

Everything else that's "Stored" is in:
```
/home/amp/.ampdata/instances/GroundBranch01/ground-branch/476400/GroundBranch/
```

Not super sure I understood though.

**Comment by Greelan** [comment]
> 

Most game servers produce saves of the world/game being run. So eg they can be re-launched later. 

The unofficial wiki suggests save game data is produced: https://unofficialgroundbranchwiki.com/en/dedicated-servers/getting-started. But I wasn't able to find anything in the listed windows location, and the listed Linux one is not relevant when using wine (also couldn't find anything in the wine prefix). Wasn't sure tho whether the files are saved only when someone joins the server.

**Comment by Greelan** [comment]
@IceOfWraith , please review

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
