### PR TITLE
Update enshrouded.kvp

### PR DESCRIPTION
**Pull request by rezor92**
Add regex to get peers (players)

### CODE REVIEW

**Comment by Greelan** [comment]
Can you post the log lines please?

**Comment by rezor92** [comment]
If first player joins:
`[online] Added Peer #0.`

If second player joins:
`[online] Added Peer #1.`

If second player leaves:
`[online] Removed Peer #1.`

If first player leaves:
`[online] Removed Peer #0.`

image

**Comment by Greelan** [comment]
Thanks. Can you share the actual AMP logs rather than just console, as the console can be normalised.

**Comment by rezor92** [comment]
Sure
[AMPLOG 2024-01-27 09-25-27.log](https://github.com/CubeCoders/AMPTemplates/files/14075253/AMPLOG.2024-01-27.09-25-27.log)
[enshrouded_server_2024-01-26T17-02-01.log](https://github.com/CubeCoders/AMPTemplates/files/14075254/enshrouded_server_2024-01-26T17-02-01.log)

**Comment by Greelan** [comment]
Thanks for this BTW. It was incorporated into another update just merged.

**Pull request closed without merging**
