### PR TITLE
Add Wolfenstein: Enemy Territory

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by IceOfWraith** [comment]
When the update bug gets fixed, this does look good to go.

**Comment by Greelan** [comment]
See you in a few months. Lol

**Comment by Greelan** [comment]
Updating seems to be OK now

**Review by IceOfWraith — DISMISSED** [review]

**Comment by IceOfWraith** [comment]
Accidentally did approve, but need to update the links for downloading.

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
