### PR TITLE
Various: update tar commands

### PR DESCRIPTION
**Pull request by Greelan**
Rely on $PATH rather than assuming location

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]

**Comment by Maxfojtik** [comment]
This commit prevented the instance from extracting when doing a fresh install

**Comment by Greelan** [comment]
As the `amp` user, what is the output of:
`which tar`
`echo $PATH`

Also, is the instance in docker?

**Comment by Maxfojtik** [comment]
/usr/bin/tar
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
yes it is in a docker

Welp, I went back to the "CubeCoders/AMPTemplates" Configuration Repository to try to replicate the issue and of course it started working. It was complaining about not having an end quote on the command for extraction. 

https://discourse.cubecoders.com/t/update-failure-with-factorio-factorio-update-failing/18196

this is a forum post describing the issue I had created by someone else

**Comment by Greelan** [comment]
Yes, that was related to the .NET 8 update and its ability to handle escaping 

That's why the release notes said you needed to update your instances from ADS to refresh the template config

**Pull request merged**
