### PR TITLE
Risk Of Rain 2: Add mod functionality, tweak settings and metaconfig

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by darkace1998** [comment]
i tested your template server installes normal and starts without problems only thing is that we get a lobby bug on joining the dedicated server gitting this error on winodows linux and from lan and wan connections

**Comment by Greelan** [comment]
What do you mean by "lobby bug"?

**Comment by darkace1998** [comment]
Lobby bug is join can join the server but you cant select any characters and skills.

its just a blank lobby without any context

**Comment by darkace1998** [comment]
@Greelan i fixed the problem you can only join a dedicated server if cross play is disabled in the client game settings

**Comment by darkace1998** [comment]
after looking at the template mode i found that the docker restrictions(CPU,RAM limits) are not working.

and the Port allocation is broken the server only looks at port 27015 even if u deploy multiple templates.

**Comment by IceOfWraith** [comment]
It sounds like you're having unrelated issues to this template. I'd tale to the Discord in the tech-support section.

**Comment by Greelan** [comment]
On the second issue, you may not have the latest templatel

**Review by IceOfWraith — APPROVED** [review]
All worked find here. Nice work getting the mods working!

**Pull request merged**
