### PR TITLE
Arma3 and DayZ: simplify mod handling

### PR DESCRIPTION
**Pull request by Greelan**
Use AMP's now inbuilt mod symlinking

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]
Seems good to me. Is there a reason for the script versus just putting it directly into the update stage?

**Comment by IceOfWraith** [comment]
I should have asked "What's the reason?" because there's always a reason with you. Lol

**Comment by Greelan** [comment]
I tried it directly - that is my strong preference - but with all the escaping required due to it being included in json, it didn't work. Maybe I didn't translate it properly, but I didn't have hours to devote to figuring it out.

**Comment by IceOfWraith** [comment]
Completely understand that. Lol

**Pull request merged**
