### PR TITLE
Add Abiotic Factor

### LINKED ISSUE #758: Abiotic Factor
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:
Game Title: Abiotic Factor
Early access UE5 

I've attempted to create a configuration, however I don't find them when fetching latest in AMP.
(https://github.com/BlueBackbite/Custom-AMP-Templates)
So I can't validate that I've setup the configuration correctly. 

Developer Guides: https://github.com/DFJacob/AbioticFactorDedicatedServer/wiki/Guide-‐-Quickstart

How to obtain:
Store Page: https://store.steampowered.com/app/427410/Abiotic_Factor/
Dedicated Server: https://steamdb.info/app/2857200/

Suppoted OSs: Windows
Supports RCON/Console input? Presumably.

Any feedback on what I'm doing wrong in terms of fetching custom instances would be appreciated as well.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

### PR DESCRIPTION
**Pull request by Greelan**
Closes #758

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]
Continence Speed Multiplier is officially my second favorite setting of any game server aside from Conan's nudity level.

**Comment by mccore** [comment]
Sorry to necro this thread @IceOfWraith and @Greelan but I think I have found an issue with the .kvp. I have tried setting the server up in AMP but cannot locate the server via the in game browser. It looks to me that [line #85](https://github.com/CubeCoders/AMPTemplates/pull/771/commits/7135349844a696cd417b91676695d1f2d9bf5297#diff-731a9450b22d7d52cb0ea4447aeab08f6e7955453018a019e680db89b1bde4efR85) should include both the -PORT flag and the -QueryPort flag. This is also reflected in the [server documentation](https://github.com/DFJacob/AbioticFactorDedicatedServer/wiki/Guide-%E2%80%90-Quickstart) provided by the game devs. This would likely also require an "AF Server Settings" option for the game port to be able to change it from the default of 7777.

**Comment by Greelan** [comment]
No, the server uses steam sockets and the game port doesn't actually listen or make a difference. Despite what their docs say (most devs don't know how their own dedicated servers work).

Have you forwarded you query port?

**Comment by mccore** [comment]
@Greelan I have indeed forwarded the query port as well as port 7777 since . Other than that all I did was change the name of the server and add a password. 

I do see the following in the log though:
`[2024.05.31-16.15.28:739][ 0]LogNet: GameNetDriver SteamNetDriver_2147482351 IpNetDriver listening on port 7777`

**Comment by mccore** [comment]
I found the issue. The name of my server has spaces in it and for whatever reason that was causing an issue with the search functionality in the game

**Pull request merged**
