### PR TITLE
Add Path of Titans

### PR DESCRIPTION
**Pull request by Greelan**
Adds Path of Titans dedicated server

### CODE REVIEW

**Comment by Greelan** [comment]
Affected by this issue: https://github.com/CubeCoders/AMP/issues/719

**Comment by IceOfWraith** [comment]
Why is there no confirmation for marking ready for review on mobile? I click it just by scrolling by it.

**Review by IceOfWraith — CHANGES_REQUESTED** [review]
Very minor issue. There's some creative stuff going on with this template. Nice work!

**Review by IceOfWraith — APPROVED** [review]
If you don't have any other changes to make, this one looks good. I don't own the game to even download the server, but it seems Arc has tested it with their customers.

**Pull request merged**
