### PR TITLE
Terratech worlds server

### PR DESCRIPTION
**Pull request by Airfirewall**
For windows and Linux, Requires wine to be able to run on Linux. There is no console yet for this server so server messages such as joining and leaving is only in log file. Log file for the server is located at 2533070\TT2\Saved\Logs. If you know a way to get the data from the logs to the console then let me know.

### CODE REVIEW

**Comment by Greelan** [comment]
Try: `-stdout -FullStdOutLogOutput` on the command line

**Comment by IceOfWraith** [comment]
You'll need to rever the manifest.json.

**Comment by IceOfWraith** [comment]
You'll need to revert the manifest.json.

**Comment by Airfirewall** [comment]
I thought you said I had to put my own manifest in the main, Ill revert it

**Comment by IceOfWraith** [comment]
No worries. Just when you're testing you need the manifest in your branch to be different. The merge can't change it.

**Comment by Airfirewall** [comment]
ok so only the template files go into main, I tried -stdout -FullStdOutLogOutput and it didn't change the console.

**Comment by Greelan** [comment]
Given the server config is just JSON, why have you used template merge? That's best avoided if possible

**Comment by Greelan** [comment]
If you make the change to json automap (or justify why template merge is appropriate), I will then provide my other improvements

**Comment by Airfirewall** [comment]
I seen other templates using it so figured it was fine, updated the configs to have it removed

**Review by Greelan — APPROVED** [review]

**Pull request merged**
