### PR TITLE
Update broke-protocol.kvp

### PR DESCRIPTION
**Pull request by gOOvER**
He is not the author. I created this tamplate

### CODE REVIEW

**Comment by IceOfWraith** [comment]
He completely remade the template because it was broken.

**Comment by gOOvER** [comment]
> He completely remade the template because it was broken.

STOP That, thats not True.- The copyright is on my side

**Comment by gOOvER** [comment]
The original is mine. So the copyright is mine. Either the author is changed or I prohibit the further use of this template.

**Comment by gOOvER** [comment]
> He completely remade the template because it was broken.
> 
> [01d405e](https://github.com/CubeCoders/AMPTemplates/commit/01d405e4d711ac015d218e31ec2dcb44773aa7b6)

lol? Only a new commit :D

**Comment by IceOfWraith** [comment]
You don't own the copyright. Not only did Greelan rewrite the template from scratch since yours was not functional (not sure why it ever got merged in the first place). This repo has no license specified which means it's all rights reserved. So whatever way you want to argue your point, it's not correct.

**Pull request closed without merging**
