### PR TITLE
Various: updates for Wine process monitoring

### PR DESCRIPTION
**Pull request by Greelan**
Oops - missed pages 2 and 3

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]
I thought the list seemed small, but figured I was misremembering. x)

Thanks for updating all of these!!!

**Comment by Greelan** [comment]
It's theoretical anyway since config refreshing is busted lmao

**Comment by IceOfWraith** [comment]
Too Frickin Shay

**Comment by Greelan** [comment]
I hope you catered for spaces in paths - looking at `Risk of Rain 2.exe`

**Comment by IceOfWraith** [comment]
I actually planned on testing that out when looking through these. It *should* but I never assume anything.

**Comment by IceOfWraith** [comment]
Works like a charm.

**Pull request merged**
