### PR TITLE
Update enshrouded.kvp

### PR DESCRIPTION
**Pull request by Dalarialus**
Fix player names being correctly recorded in analytics by updating RegEx.

This is my first time modifying a RegEx, so I'd appreciate it if someone more knowledgeable can check my work.

### CODE REVIEW

**Comment by Dalarialus** [comment]
Indeed! [PasteBin](https://pastebin.com/CF9Fu98B)

**Comment by Dalarialus** [comment]
Apologies if there is an established procedure that I'm not following - This is my first time ever making a pull request :)

**Comment by Greelan** [comment]
It's just that I can't verify the regex without the underlying logs. xD

You can test and verify regex at regex101.com.

I had to make some tweaks to the capture groups for them to work.

Thanks for raising this.

**Review by Greelan — APPROVED** [review]
Approved with changes

**Comment by Dalarialus** [comment]
Thanks! :)

**Pull request merged**
