### PR TITLE
Update Randompassword Inputs

### PR DESCRIPTION
**Pull request by IceOfWraith**

### CODE REVIEW

**Review by Greelan — COMMENTED** [review]
Suggest `{{newguid()}}` for those settings that otherwise supply a default value

**Comment by IceOfWraith** [comment]
Good call. Got them updated now.

**Review by Greelan — COMMENTED** [review]
Don't add it to SE or The Forest

**Comment by IceOfWraith** [comment]
I placed it on all so they'd have a default secure password in case the user never puts one in.

**Comment by Greelan** [comment]
Thought you were big on dev defaults? :)

For many servers, blank password = not enabled.

Anyway, for SE at least it seems the UUIDv4 format doesn't work anyway, so what's the point?

**Comment by IceOfWraith** [comment]
I said I *prefer* to keep dev defaults. But they aren't always good with security. Lol

Anyways, I've made the changes if you want to review.

**Review by Greelan — APPROVED** [review]

**Pull request merged**
