### PR TITLE
Add SCP: Secret Laboratory

### PR DESCRIPTION
**Pull request by Greelan**
Work in progress

### CODE REVIEW

**Comment by Computermaster20** [comment]
Hows this coming along? Need this for a new server setup please.

**Comment by IceOfWraith** [comment]
Just waiting on a review now that it's finished up.

**Comment by Greelan** [comment]
It's come along well, despite no-one who has been asking for it contributing any testing and feedback lol

**Review by IceOfWraith — APPROVED** [review]
I'm going to go ahead and approve this one. I've requested approval to get my test server listed, but haven't heard back yet. I'll leave it up to you if you want to wait for that process before merging.

**Comment by Greelan** [comment]
Thanks, happy to wait. Appreciate your testing it so thoroughly.

**Comment by IceOfWraith** [comment]
Testing of the public server was a success. Player tracking and everything seems to be working well. Nice work!

**Comment by ssfdre38** [comment]
Client side everything looks good.

**Comment by Greelan** [comment]
Ready now. Thanks again for testing

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
