### PR TITLE
Update abiotic-factor.kvp - Regex Fixes - Join + Leave + Chat

### PR DESCRIPTION
**Pull request by sxon-xo**
Logs from the server for validation. Tested by myself.

Join:

`[2024.08.31-18.10.13:686][767]LogAbiotic: Display: CHAT LOG: SamXon has entered the facility. [2024.08.31-18.10.13:686][767]LogGameMode: Display: Match State Changed from WaitingToStart to InProgress [2024.08.31-18.10.13:689][767]AnimBlueprintLog: Warning: SLOTNODE: 'DefaultSlot' in animation instance class FPArms_AnimBP_C already exists. Remove duplicates from the animation graph for this class. [2024.08.31-18.10.13:695][767]LogGameState: Match State Changed from WaitingToStart to InProgress [2024.08.31-18.10.13:695][767]LogNet: Join succeeded: SamXon 11:10:14`

Leave:

`[2024.08.31-18.11.29:506][ 63]LogAbiotic: Display: CHAT LOG: SamXon has exited the facility. [2024.08.31-18.11.29:506][ 63]LogOnline: STEAM: Removing P2P Session Id: UNKNOWN [0x110000101F71F63], Channel: 7777, IdleTime: 0.037 11:11:30
[2024.08.31-18.11.30:521][ 93]LogSaveWorld: Display: Finished autosaving 11:11:31`

Chat:

`11:19:11
[2024.08.31-18.19.11:111][766]LogAbiotic: Display: CHAT LOG: SamXon testing 11:19:12
[2024.08.31-18.19.12:197][799]LogAbiotic: Display: CHAT LOG: SamXon testing`

### CODE REVIEW

**Comment by Greelan** [comment]
Thanks. Can you post logs from AMP_Logs rather than console?

**Comment by sxon-xo** [comment]
> Thanks. Can you post logs from AMP_Logs rather than console?

`[2024.08.31-18.27.42:279][981]LogOnline: STEAM: AUTH HANDLER: Sending auth result to user 76561197993238371 with flag success? 1
[2024.08.31-18.27.42:312][982]LogNet: NotifyAcceptingChannel Control 0 server World /Game/Maps/Facility.Facility: Accepted
[2024.08.31-18.27.42:312][982]LogNet: Remote platform little endian=1
[2024.08.31-18.27.42:312][982]LogNet: This platform little endian=1
[2024.08.31-18.27.42:345][983]LogNet: Login request: ?Name=SamXon??PW=xxx?ConnectID=76561197993238371 userId: STEAM:UNKNOWN [0x110000101F71F63] platform: STEAM
[2024.08.31-18.27.43:006][  3]LogNet: Client netspeed is 640000
[2024.08.31-18.27.43:006][  3]LogNet: Join request: /Game/Maps/ServerEntry?Name=SamXon??PW=xxx?ConnectID=76561197993238371?SplitscreenCount=1
[2024.08.31-18.27.43:008][  3]LogAbiotic: Display: CHAT LOG:  SamXon has entered the facility.
[2024.08.31-18.27.43:008][  3]LogGameMode: Display: Match State Changed from WaitingToStart to InProgress
[2024.08.31-18.27.43:011][  3]AnimBlueprintLog: Warning: SLOTNODE: 'DefaultSlot' in animation instance class FPArms_AnimBP_C already exists. Remove duplicates from the animation graph for this class.
[2024.08.31-18.27.43:016][  3]LogGameState: Match State Changed from WaitingToStart to InProgress
[2024.08.31-18.27.43:017][  3]LogNet: Join succeeded: SamXon
[2024.08.31-18.27.44:058][ 33]LogGameplayTags: NetworkGameplayTagNodeIndexHash is 833ce32a
[2024.08.31-18.27.48:000][153]LogOnlineSession: Warning: STEAM: Server setting ,StoryProgress_s:Office3 overflows Steam SetGameTags call
[2024.08.31-18.27.48:000][153]LogOnlineSession: Warning: STEAM: Server setting ,ModifiedRuleset_i:0 overflows Steam SetGameTags call
[2024.08.31-18.27.49:278][191]LogAnimation: Warning: SLOTNODE: 'LeftArm' in animation instance class ABF_Scientist_AnimBP_C already exists. Remove duplicates from the animation graph for this class.
[18:27:53] [Generic:samxon Chat/12] : SamXon: testing
[2024.08.31-18.27.53:559][321]LogAbiotic: Display: CHAT LOG: SamXon testing
[2024.08.31-18.32.46:285][187]LogSaveWorld: Display: Finished autosaving
[18:35:51] [Generic:samxon Chat/12] : SamXon: testing 2
[2024.08.31-18.35.51:352][794]LogAbiotic: Display: CHAT LOG: SamXon testing 2
[2024.08.31-18.36.05:180][213]LogNet: UChannel::ReceivedSequencedBunch: Bunch.bClose == true. ChIndex == 0. Calling ConditionalCleanUp.`


`[2024.08.31-18.36.05:180][213]LogNet: UChannel::CleanUp: ChIndex == 0. Closing connection. [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 76561197993238371:7777, Name: SteamNetConnection_2147481995, Driver: GameNetDriver SteamNetDriver_2147482336, IsServer: YES, PC: Abiotic_PlayerController_C_2147481985, Owner: Abiotic_PlayerController_C_2147481985, UniqueId: STEAM:UNKNOWN [0x110000101F71F63]
[2024.08.31-18.36.05:180][213]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 76561197993238371:7777, Name: SteamNetConnection_2147481995, Driver: GameNetDriver SteamNetDriver_2147482336, IsServer: YES, PC: Abiotic_PlayerController_C_2147481985, Owner: Abiotic_PlayerController_C_2147481985, UniqueId: STEAM:UNKNOWN [0x110000101F71F63], Channels: 340, Time: 2024.08.31-18.36.05
[2024.08.31-18.36.05:180][213]LogNet: UNetConnection::SendCloseReason:
[2024.08.31-18.36.05:180][213]LogNet:  - Result=ControlChannelClose, ErrorContext="ControlChannelClose"
[2024.08.31-18.36.05:180][213]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 76561197993238371:7777, Name: SteamNetConnection_2147481995, Driver: GameNetDriver SteamNetDriver_2147482336, IsServer: YES, PC: Abiotic_PlayerController_C_2147481985, Owner: Abiotic_PlayerController_C_2147481985, UniqueId: STEAM:UNKNOWN [0x110000101F71F63]
[2024.08.31-18.36.05:216][214]LogAbiotic: Display: CHAT LOG:  SamXon has exited the facility.
[2024.08.31-18.36.05:217][214]LogOnline: STEAM: Removing P2P Session Id: UNKNOWN [0x110000101F71F63], Channel: 7777, IdleTime: 0.037
[2024.08.31-18.36.06:232][244]LogSaveWorld: Display: Finished autosaving
[2024.08.31-18.36.06:730][261]LogOnline: STEAM: Closing channel 7777 with user 76561197993238371
[2024.08.31-18.36.06:732][261]LogOnline: STEAM: 76561197993238371 has been removed.
[2024.08.31-18.36.10:193][367]LogOnlineSession: Warning: STEAM: Server setting ,StoryProgress_s:Office3 overflows Steam SetGameTags call
[2024.08.31-18.36.10:193][367]LogOnlineSession: Warning: STEAM: Server setting ,ModifiedRuleset_i:0 overflows Steam SetGameTags call
[2024.08.31-18.36.11:242][396]LogUObjectHash: Compacting FUObjectHashTables data took   2.96ms
[2024.08.31-18.37.46:481][273]LogSaveWorld: Display: Finished autosaving
[2024.08.31-18.51.42:964][527]LogAbiotic: Display: Creating save backup for: Cascade
[2024.08.31-18.51.42:965][527]LogAbiotic: Display: Found index 5 to use as backup for save Cascade, beginning now...
[2024.08.31-18.51.42:965][527]LogAbiotic: Display: Existing backup found, deleting: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/5
[2024.08.31-18.51.42:967][527]LogAbiotic: Display: Copying directory tree: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/5 Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Worlds/Cascade
[2024.08.31-19.21.48:007][ 16]LogAbiotic: Display: Creating save backup for: Cascade
[2024.08.31-19.21.48:007][ 16]LogAbiotic: Display: Found index 1 to use as backup for save Cascade, beginning now...
[2024.08.31-19.21.48:007][ 16]LogAbiotic: Display: Existing backup found, deleting: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/1
[2024.08.31-19.21.48:010][ 16]LogAbiotic: Display: Copying directory tree: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/1 Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Worlds/Cascade
[2024.08.31-19.51.53:042][497]LogAbiotic: Display: Creating save backup for: Cascade
[2024.08.31-19.51.53:043][497]LogAbiotic: Display: Found index 2 to use as backup for save Cascade, beginning now...
[2024.08.31-19.51.53:043][497]LogAbiotic: Display: Existing backup found, deleting: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/2
[2024.08.31-19.51.53:045][497]LogAbiotic: Display: Copying directory tree: Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Backups/Cascade/2 Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved/SaveGames/Server/Worlds/Cascade`




Seems like you can use lognet for joining as an alternative if you have the option for player joins and leaves to not be displayed in chat. For player leaves im not sure what can be done since it doesn't list the name. I see it lists the steamid but not sure how useful that is.

**Comment by Greelan** [comment]
These are confusing logs - everything seems to be on one line? Surely that is not how the server is logging it?

**Comment by sxon-xo** [comment]
> These are confusing logs - everything seems to be on one line? Surely that is not how the server is logging it?

Just updated my previous comment. See if that helps at all. Definitely not one line.

**Comment by Greelan** [comment]
That helps.

The problem with matching on the chat logs is that the user joins and leaves will also be matched as chat...

**Review by Greelan — APPROVED** [review]

**Comment by Greelan** [comment]
OK, will take you at your word xD

**Pull request merged**
