### PR TITLE
Add OpenRCT2

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Comment by JonathanArendt** [comment]
@Greelan 
image
I'm not sure, but I think these settings are settings for the game side of Open RCT2 not the server.

**Comment by JonathanArendt** [comment]
In fact, I think almost all of the "Gameplay Settings" are meant when you are playing the game, essentially client side settings, they may not affect a headless server.

**Comment by JonathanArendt** [comment]
IDEA, It might be nice if you have AMP create the file directory for the game files, so if you are adding the files manuly you know where to add the game files. (I have the games from the disks).

**Comment by Greelan** [comment]
I just assumed they would dictate the default setup that a client connecting would then experience. Happy to be told otherwise

**Comment by Greelan** [comment]
> IDEA, It might be nice if you have AMP create the file directory for the game files, so if you are adding the files manuly you know where to add the game files. (I have the games from the disks).

Great idea - that's what the template already does! And gives the option to not download from Steam

**Comment by JonathanArendt** [comment]
Let me do some testing to verify, but I don't believe it sets the client settings, as they are game specific not save specific.

**Comment by JonathanArendt** [comment]
> > IDEA, It might be nice if you have AMP create the file directory for the game files, so if you are adding the files manuly you know where to add the game files. (I have the games from the disks).
> 
> Great idea - that's what the template already does! And gives the option to not download from Steam

Yeah, I saw the settings for it, lol, but I didn't see the folders (didn't go deep enough). Sorry

**Comment by IceOfWraith** [comment]
I don't own the game to review fully, but everything seems to check out here otherwise. URL updates (and presumably the response from @JonathanArendt about the game settings) and this is good to go.

**Comment by Greelan** [comment]
The game is free xD

**Comment by JonathanArendt** [comment]
I was having issues allowing the user to changed out of specator mode, What I found on the server's that I had set up before, I used the openRCT.com instead of .EXE. I don't know if that's why I was unable to use the console or not.

**Comment by JonathanArendt** [comment]
> The game is free xD

I thought you needed the orriginal game files, and that's not free...

**Comment by Greelan** [comment]
True

**Comment by IceOfWraith** [comment]
Lol you had me searching wondering how I was missing the free version. Thought I was losing it more than I already am.

**Comment by Greelan** [comment]
> I was having issues allowing the user to changed out of specator mode, What I found on the server's that I had set up before, I used the openRCT.com instead of .EXE. I don't know if that's why I was unable to use the console or not.

I can change that.

What about the Gameplay Settings - did you resolve whether they are relevant?

**Comment by Greelan** [comment]
@JonathanArendt seems that the spectator issue comes from the default group assigned by the server (which is Spectator rather than User). I need to figure out how to manage that in the template

**Comment by JonathanArendt** [comment]
> > I was having issues allowing the user to changed out of specator mode, What I found on the server's that I had set up before, I used the openRCT.com instead of .EXE. I don't know if that's why I was unable to use the console or not.
> 
> I can change that.
> 
> What about the Gameplay Settings - did you resolve whether they are relevant?

So the gameplay settings are relating to the client, since the server is not a dedicated server, but reather a headless client, they are redundant and unneeded.

**Comment by JonathanArendt** [comment]
> I was having issues allowing the user to changed out of specator mode, What I found on the server's that I had set up before, I used the openRCT.com instead of .EXE. I don't know if that's why I was unable to use the console or not.

Did the resolve the issue of being able to run commands in chat?

**Comment by JonathanArendt** [comment]
{
    "default_group": 1,
    "groups": [
        {
            "id": 0,
            "name": "Admin",
            "permissions": [
                "PERMISSION_CHAT",
                "PERMISSION_TERRAFORM",
                "PERMISSION_SET_WATER_LEVEL",
                "PERMISSION_TOGGLE_PAUSE",
                "PERMISSION_CREATE_RIDE",
                "PERMISSION_REMOVE_RIDE",
                "PERMISSION_BUILD_RIDE",
                "PERMISSION_RIDE_PROPERTIES",
                "PERMISSION_SCENERY",
                "PERMISSION_PATH",
                "PERMISSION_CLEAR_LANDSCAPE",
                "PERMISSION_GUEST",
                "PERMISSION_STAFF",
                "PERMISSION_PARK_PROPERTIES",
                "PERMISSION_PARK_FUNDING",
                "PERMISSION_KICK_PLAYER",
                "PERMISSION_MODIFY_GROUPS",
                "PERMISSION_SET_PLAYER_GROUP",
                "PERMISSION_CHEAT",
                "PERMISSION_TOGGLE_SCENERY_CLUSTER",
                "PERMISSION_PASSWORDLESS_LOGIN",
                "PERMISSION_MODIFY_TILE",
                "PERMISSION_EDIT_SCENARIO_OPTIONS"
            ]
        },
        {
            "id": 1,
            "name": "Spectator",
            "permissions": [
                "PERMISSION_CHAT"
            ]
        },
        {
            "id": 2,
            "name": "Players",
            "permissions": [
                "PERMISSION_CHAT",
                "PERMISSION_TERRAFORM",
                "PERMISSION_SET_WATER_LEVEL",
                "PERMISSION_TOGGLE_PAUSE",
                "PERMISSION_CREATE_RIDE",
                "PERMISSION_REMOVE_RIDE",
                "PERMISSION_BUILD_RIDE",
                "PERMISSION_RIDE_PROPERTIES",
                "PERMISSION_SCENERY",
                "PERMISSION_PATH",
                "PERMISSION_CLEAR_LANDSCAPE",
                "PERMISSION_GUEST",
                "PERMISSION_STAFF",
                "PERMISSION_PARK_PROPERTIES",
                "PERMISSION_PARK_FUNDING",
                "PERMISSION_KICK_PLAYER",
                "PERMISSION_MODIFY_GROUPS",
                "PERMISSION_TOGGLE_SCENERY_CLUSTER",
                "PERMISSION_PASSWORDLESS_LOGIN",
                "PERMISSION_MODIFY_TILE"
            ]
        }
    ]
}

**Comment by JonathanArendt** [comment]
This is an example of groups.json from my old server.

**Comment by JonathanArendt** [comment]
[
    {
        "groupId": 0,
        "hash": "",
        "name": "Admin"
    },
    {
        "groupId": 0,
        "hash": "682c924e2e22b3f5d3a5e7b89d3f3dd6182dcfae",
        "name": "Jonathan"
    },
    {
        "groupId": 2,
        "hash": "8dc9e630b9b72850e0663cc3a8fccb112b2dafd5",
        "name": "Player1"
    },
    {
        "groupId": 2,
        "hash": "920d8c7d7ee665f1c20f8c1d358061f38e8f8e16",
        "name": "Player 2"
    }
]

**Comment by JonathanArendt** [comment]
And this is the users.json, I don't know how to find the hashes. Though they do get added when someone joins, they either need to be added into a specific group manually or using ingame by a player who already has permissions.

**Comment by Greelan** [comment]
Yeah, I saw references to groups.json and users.json online. It's not particularly user friendly, particularly given no groups.json is created by default it seems.

And, no, console still doesn't work in AMP. It is likely down to AMP not being able to handle the server console.

Starting to wonder about the overall viability of this server in AMP.

**Comment by JonathanArendt** [comment]
If you add the template above as a default downloaded for the groups.json and the issue would just be setting the player's permissions.

**Comment by Greelan** [comment]
Yes, I understand that, but it makes it hard if you can't use the console to set perms, and can't generate the hashes yourself.

**Comment by JonathanArendt** [comment]
> Yeah, I saw references to groups.json and users.json online. It's not particularly user friendly, particularly given no groups.json is created by default it seems.
> 
> And, no, console still doesn't work in AMP. It is likely down to AMP not being able to handle the server console.
> 
> Starting to wonder about the overall viability of this server in AMP.

yeah, the big issue is the lack of the console input.

**Comment by JonathanArendt** [comment]
> Yes, I understand that, but it makes it hard if you can't use the console to set perms, and can't generate the hashes yourself.

The only thing would be the server admin having to edit the user.json file.

**Comment by JonathanArendt** [comment]
I don't understand why AMP is not acting like a cmd console.
Commands work in cmd

**Comment by JonathanArendt** [comment]
With stormworks this wasn't an issue because stormworks didn't have console commands, this does and AMP should be passing them through.

**Comment by Greelan** [comment]
You do realise you can write more than 1 sentence per comment, right? Lol

I connect to the server, and don't even see my user details being populated in users.json....

**Comment by JonathanArendt** [comment]
Okay, here's an idea, have the templet default to an Admin type group with permissions, so when the admin joins he can manage the permissions ingame without needing to modify the files.

Let me look into that, there may something else that's the issue with that. I don't remember how that worked when I set up my servers.

And yes I know that I can have mulitple sentances, it's just that I don't always have all the answer's at once, lol

**Comment by IceOfWraith** [comment]
Now now, Greelan. Be nice to our new guest. He wants to help you. x)

**Comment by JonathanArendt** [comment]
Okay, I got it to work, you only get added to the users.json if you're changed from the default group. So set up a default group that gives admin privliges, and then once the player joins, they can change themselves to a "Admin group" and set the permissions for the "Default group"

**Comment by Greelan** [comment]
Ugh, so cumbersome. I will look at it further when I have time.

**Comment by JonathanArendt** [comment]
yeah, tell me about it, it only get's worse, group 0 is admin, it's what the server starts at as default, and there is no way to make a player "Root admin without setting the default permissions to 0, however this doesn't save the user, it only save's if the player changes groups, so the payer would have to set themselves a different group go back into the users.json file, change themselves back to group 0, and then change the default group to spectator, super cluncky without console commands.

**Comment by Greelan** [comment]
I did it another way. I found my key on the client, then manually edited users.json to add myself as an Admin. So when I connect in game, I am Admin

Still clunky.

**Comment by JonathanArendt** [comment]
Either way, that would be something to put in a guide for the server, and then the console is not as of an issue.

**Comment by Greelan** [comment]
Thinking I might try this: supply a users.json that has the server entry plus an additional, blank Admin entry. Then try jpath to tie that entry to settings in the UI - a bit like you did with Stormworks admins. Can't recall when I have tried jpath to a node in AMP before. So the user just has to enter their key hash and name in the UI

**Comment by Greelan** [comment]
Actually, pretty sure AMP's jpath implementation can't handle arrays...

**Comment by JonathanArendt** [comment]
If you need help let me know. I ended up setting the first child, but there should be a way to select the second.

**Comment by JonathanArendt** [comment]
https://stackoverflow.com/questions/2407781/get-nth-child-of-a-node-using-xpath 

and a quick google later, here's the answer, lol

**Comment by Greelan** [comment]
Oh, I know the jpath formatting, it's a question whether AMP can handle it. iirc I've tried before with arrays, no cigar

**Comment by JonathanArendt** [comment]
Oh i see, let me know.

**Comment by Greelan** [comment]
Yeah, AMP craps itself when trying to write

**Comment by IceOfWraith** [comment]
Just ping me when you're ready for review again.

**Comment by Greelan** [comment]
@JonathanArendt I've removed the gameplay settings (confirmed in-game that they don't affect anything), added a note re adding admins, and also now supply a default groups.json but with the default group being 2 (User), rather than 1 (Spectator). Let me know thoughts.

**Comment by JonathanArendt** [comment]
Did you get jpath to select first element? If not can you send me what you tried and I can see if I can get it to work? If you want.

**Comment by Greelan** [comment]
I tried, it doesn't work. AMP's json lib can't handle arrays. You can play around if you want. I don't have what I did anymore since I just tried variations on an existing instance

**Comment by JonathanArendt** [comment]
How do I test changes without commiting to github?

**Comment by Greelan** [comment]
Create an instance, modify the instance files locally (configmanifest.json in particular in this case)

**Comment by Greelan** [comment]
@IceOfWraith this can be reviewed too

**Comment by IceOfWraith** [comment]
Everything looks good if you want to update the links.

**Comment by JonathanArendt** [comment]
I got an answer from Peonoix this is the proper syntax for the users.java. $[1].name

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JonathanArendt** [comment]
I will try to test this really quick before work

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
