### PR TITLE
Add Foundry Virtual Tabletop

### PR DESCRIPTION
**Pull request by Greelan**
Adds Foundry Virtual Tabletop dedicated server

Note:
- Both Linux and Windows are supported - the template is configured to download its own Node.js, and so is able to run on each platform regardless of whether Node.js, or the correct version, is otherwise installed on the system. The UI allows selection by the user of the desired version (must be at least v14.x)
- The user is required to supply a (timed) download URL from the Foundry VTT login portal in order to download/update the server
- Minimal settings are configured given that the server has a web interface for configuring them, and in many cases AMP can't handle them anyway (due to starting `null` values)

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]
As discussed, I don't own so only a desktop review. Looks good though.

**Review by IceOfWraith — APPROVED** [review]
Everything seems okay, as much as I can test without owning it.

**Review by IceOfWraith — APPROVED** [review]

**Comment by Greelan** [comment]
Thanks. It's been tested by a couple of other people in Discord and no issues.

I've updated the extra steps URI to point to Discourse.

**Comment by Greelan** [comment]
After the next AMP release I will add ARM support.

**Pull request merged**
