### PR TITLE
Update squad-dedicated-server.kvp

### PR DESCRIPTION
**Pull request by southnode**
Update to add EOS compatibility port

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]

**Comment by Greelan** [comment]
Had this been tested on an existing instance? Given AMP won't add the port to existing instances, the command line arg will not be populated properly. Curious if that breaks the server

**Comment by southnode** [comment]
> Had this been tested on an existing instance? Given AMP won't add the port to existing instances, the command line arg will not be populated properly. Curious if that breaks the server

Yeah unfortunately existing instances flat out don't work as-is, and will need to be redeployed. Developers practically introduced EOS backend switch overnight. Caused all sorts of mischief.

**Comment by Greelan** [comment]
Still, AMP should handle adding the ports, so you wouldn't need to totally redeploy. Such a missing link

**Comment by southnode** [comment]
Agreed. If ports are added with a new config, AMP should integrate them.

**Pull request merged**
