### PR TITLE
Kingdom of Atham

### PR DESCRIPTION
**Pull request by tempusthales**
Initial Commit for Kingdom of Atham: Crown of Champions

### CODE REVIEW

**Comment by tempusthales** [comment]
Please add labels: Windows...

**Comment by Greelan** [comment]
No port variables defined in the kvp?

**Comment by IceOfWraith** [comment]
Your config manifest needs some reviewing. I see some checkboxes are enum, max users isn't using $MaxUsers, and some other capitalization inconsistencies. Please test your template to verify which settings are working.

**Comment by tempusthales** [comment]
Thanks for all the pointers, I brought it here exactly for this.  Will work on it, test and update here.

**Comment by IceOfWraith** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
