### PR TITLE
(terraria) Hardcode metaconfig reference in args directly to avoid bug

### PR DESCRIPTION
**Pull request by jasperfirecai2**
see https://github.com/CubeCoders/AMP/issues/1147 for the bug in question

### CODE REVIEW

**Comment by Greelan** [comment]
Lol, I beat you to it: #946

**Review by Greelan — APPROVED** [review]

**Comment by Greelan** [comment]
Actually, I've approved and merged yours so I don't have to wait for Ice :)

**Comment by jasperfirecai2** [comment]
Lol yeah sorry for the delay i wasn't home for like 36 hours straight

**Comment by IceOfWraith** [comment]
I'm no longer useful.

**Pull request merged**
