### PR TITLE
Conan Exiles Regex and Exit

### PR DESCRIPTION
**Pull request by rezor92**
Changed commandline args as suggested by @Greelan which makes it possible to search for regex 
Added regex for join leave and chat. Modified regex for ready. 
Modified exit mode to string and set timeout to 60s so that the server can properply shutdown

### CODE REVIEW

**Comment by Greelan** [comment]
Couple of comments:
- With the new command line args, you shouldn’t need `-log`. They are meant to be a replacement.
- Have you tested this on both Linux and Windows? AMP’s console in Linux tends to be better, and even in cases where the additional command line args help, usually only `-stdout` is wanted/needed, as otherwise the log lines get repeated.
- Is it appropriate to capture `#12345` as part of the username capture group?

**Comment by rezor92** [comment]
> Couple of comments:
> 
> * With the new command line args, you shouldn’t need `-log`. They are meant to be a replacement.
> * Have you tested this on both Linux and Windows? AMP’s console in Linux tends to be better, and even in cases where the additional command line args help, usually only `-stdout` is wanted/needed, as otherwise the log lines get repeated.
> * Is it appropriate to capture `#12345` as part of the username capture group?

- You are right `-log` isn't needed but `-stdout -FullStdOutLogOutput` are both required otherwise the server will not output the messages required for regex
- I've tested this only on Windows but I think the behavior should be the same on Linux
- Yes the `#12345` is part of the unique username of players. For example there could be `johndoe#12345` and `johndoe#45678` playing at the same time

**Comment by Greelan** [comment]
> * I've tested this only on Windows but I think the behavior should be the same on Linux
You are probably right given the server is being run with Wine on Linux, *but* assumptions don't get PRs merged. :)

I don't have the client to test, so someone else will need to try this out on Linux.

**Comment by rezor92** [comment]
> > * I've tested this only on Windows but I think the behavior should be the same on Linux
> 
> You are probably right given the server is being run with Wine on Linux, _but_ assumptions don't get PRs merged. :)
> 
> I don't have the client to test, so someone else will need to try this out on Linux.

Works on Linux
image

**Comment by Greelan** [comment]
Thanks for testing. I do note that some log lines are repeated in the Linux console. Is that the same on Windows?

**Comment by rezor92** [comment]
> Thanks for testing. I do note that some log lines are repeated in the Linux console. Is that the same on Windows?

Which log lines do you mean?

**Comment by Greelan** [comment]
A few examples from the end of the startup:

```
SourceServerQueries:Warning: Started SourceServerQueries on port 27021
[2023.01.28-08.10.20:342][  0]SourceServerQueries:Warning: Started SourceServerQueries on port 27021
...
LogStreaming:Warning: Took 106.78ms to ProcessLoadedPackages
[2023.01.28-08.10.21:978][ 37]LogStreaming:Warning: Took 106.78ms to ProcessLoadedPackages
Network:Display: Key Distribution Service websocket connected successfully.
[2023.01.28-08.10.22:286][ 44]Network:Display: Key Distribution Service websocket connected successfully.
Network:Display: Key distribution web service: Connected (session: F6A21B81418CB20C364E5B972F590866, mirror: wss://ce-kds-winunoff-ams06.funcom.com:7005/server/, fail count: 0, retry time: -1.0)
[2023.01.28-08.10.22:287][ 44]Network:Display: Key distribution web service: Connected (session: F6A21B81418CB20C364E5B972F590866, mirror: wss://ce-kds-winunoff-ams06.funcom.com:7005/server/, fail count: 0, retry time: -1.0)
LogStreaming:Warning: Took 175.20ms to ProcessLoadedPackages
[2023.01.28-08.10.22:464][ 44]LogStreaming:Warning: Took 175.20ms to ProcessLoadedPackages
...
LogLevel:Warning: Failed to find streaming level object associated with 'Event_WitchHunt_04'
[2023.01.28-08.10.23:525][ 74]LogLevel:Warning: Failed to find streaming level object associated with 'Event_WitchHunt_04'
```

This is not uncommon on Linux with the enhanced logging for UE4 games - the console is already receiving the logs, and the enhanced logging sends it again.

**Comment by rezor92** [comment]
Seems to be Linux exclusive

```
[2023.01.27-23.03.52:263][  1]SourceServerQueries:Warning: Started SourceServerQueries on port 27015
[2023.01.27-23.03.52:273][  1]LogDreamworld:Display: SQLLite query data for TEXT (char*) at column 2 and row 0 result 0 is null, will return empty string instead
[2023.01.27-23.03.52:282][  1]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_01 1 1 0
[2023.01.27-23.03.52:609][  2]ConanSandbox:Display: Character ID 17 has name ... and guild ID 128.
[2023.01.27-23.03.52:640][  2]ItemInventory:Error: Data: DLC recipe 100016 can not be learned this way.
[2023.01.27-23.03.52:668][  2]ConanSandbox:Display: Character ID 139 has name ... and guild ID 128.
[2023.01.27-23.03.52:814][  3]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_02 1 1 0
[2023.01.27-23.03.52:846][  5]Network:Display: Key Distribution Service websocket connected successfully.
[2023.01.27-23.03.52:881][  6]Network:Display: Key distribution web service: Connected (session: E14B0A094CC49BBF2F1B1EAAEB46CEFB, mirror: wss://ce-kds-winunoff-wdc08.funcom.com:7007/server/, fail count: 0, retry time: -1.0)
[2023.01.27-23.03.52:907][  6]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_03 1 1 0
[2023.01.27-23.03.53:146][ 12]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_05 1 1 0
[2023.01.27-23.03.53:246][ 15]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_01 1 1 0
[2023.01.27-23.03.53:280][ 16]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_02 1 1 0
[2023.01.27-23.03.53:312][ 17]LogLevel: ActivateLevel /Game/Maps/ConanSandbox/Events_Testing/EventLevels/Event_Witchhunt_03 1 1 0
[2023.01.27-23.03.53:346][ 18]LogLevel:Warning: Failed to find streaming level object associated with 'Event_WitchHunt_04'
```

**Comment by Greelan** [comment]
So the question is whether the log lines for user joins, leaves etc already appear on Linux without the command line flag changes? If so, you could make those changes platform-specific.

**Comment by rezor92** [comment]
> So the question is whether the log lines for user joins, leaves etc already appear on Linux without the command line flag changes? If so, you could make those changes platform-specific.

Tried it, but it's not working on linux without the `-stdout -FullStdOutLogOutput` arguments.

**Review by IceOfWraith — APPROVED** [review]
These changes look great! I've thoroughly tested on Linux and Windows and found the same result that both args are needed to get the output. Unfortunately, that means duplicate output like 7d2d.

**Pull request merged**
