### PR TITLE
Added Darkness Falls Mod

### PR DESCRIPTION
**Pull request by gkuba**
Added Darkness Falls mod download toggle to the SteamCMD and Updates category as there are no extra config settings. 

Tested and working on both Linux and Windows.

seven-days-to-dieconfig.json
- Added the Darkness Falls toggle under SteamCMD and Updates category

seven-days-to-dieupdates.json
- Added the zip download from the Darkness Falls gitlab repo. 
- Added copy and delete command to pull the files from the unzipped folder to the root folder and delete it when its done for both Linux and Windows.

### CODE REVIEW

**Comment by gkuba** [comment]
Ready for review

**Review by IceOfWraith — APPROVED** [review]
Looks good! As soon as you merge this, I have an update to put out as well.

**Comment by gkuba** [comment]
@IceOfWraith I don't have access to merge. But ty for verifying this.

**Comment by IceOfWraith** [comment]
Lol yeah... poor word choice. I actually DM'ed you on Discord asking if it was ready to merge. :)

**Pull request merged**
