### PR TITLE
Update conan-exiles.kvp

### PR DESCRIPTION
**Pull request by IceOfWraith**
Update to include non-Steam client mod downloading port.

### CODE REVIEW

**Review by Greelan — COMMENTED** [review]
Should it be "Game and Mods Port"?

Also, would it be worth hardcoding the offset (hopefully an ini command line arg works) so that users can't change and mess up the port setup?

**Comment by IceOfWraith** [comment]
You're right. Even after you corrected what I put I still read it wrong. Lol

Can you elaborate what you mean for the offset?

**Comment by Greelan** [comment]
From the wiki:

`Default value: 0 (offset added to the game port)
Config file: Engine.ini, section: “[/Script/ConanSandbox.SystemSettings]”, entry: “ModFileDownload.DownloadPortOffset=2”`

So if the ini command line arg works it would be:

`ini:Engine:[/Script/ConanSandbox.SystemSettings]:ModFileDownload.DownloadPortOffset`

With a hardcoded value of 0 set in a hidden config manifest setting

**Comment by Greelan** [comment]
Or just add directly to the command line args (like I did for The Isle):

`-ini:Engine:[/Script/ConanSandbox.SystemSettings]:ModFileDownload.DownloadPortOffset=0`

**Comment by IceOfWraith** [comment]
Ahh okay. I follow. Yeah let me do that. The ini command line doesn't work last we tried but I can put it in the config manifest.

**Comment by Greelan** [comment]
It worked some of the time for AdminPassword if I recall... Lol

But the hidden setting to overwrite it if someone adds it to Engine.ini will also address it, given the default is what we want

**Comment by IceOfWraith** [comment]
Well, that won't be necessary. Because it's already the second setting in the config manifest. x)

**Comment by Greelan** [comment]
Lmao, you pre-emptied yourself

**Review by Greelan — APPROVED** [review]

**Pull request merged**
