### PR TITLE
Add Longvinter

### PR DESCRIPTION
**Pull request by Greelan**
Tested by winglessraven and TempusThales (as per comments on Discord)

### CODE REVIEW

**Comment by IceOfWraith** [comment]
I see there's a Linux server as well. Is there an issue running that in AMP?

**Comment by Greelan** [comment]
Yes, it needs a GH repo to be cloned

**Comment by IceOfWraith** [comment]
Can you not use the zip link for the repo?

https://github.com/Uuvana-Studios/longvinter-linux-server/archive/refs/heads/main.zip

**Comment by Greelan** [comment]
Ha, whaddya know. Didn't see that (recent addition maybe?). Will add and test.

**Comment by IceOfWraith** [comment]
You can get that from clicking the green Code button and right click Download ZIP. Kind of hidden. Plus there's no guarantee AMP will let you download it to the same working directory.

One other thing I note is there's a query port but no EndpointURI. Does it support that? Otherwise, it seems good to go.

**Comment by Greelan** [comment]
I like the idea of the GH zip download, but it creates an additional subdir (the zip folder name) and so messes up the working dir

**Comment by IceOfWraith** [comment]
Could you have the Steam download go to the same folder? Then adjust accordingly?

**Comment by Greelan** [comment]
I know what you mean. It may not matter though, continuing to test

**Comment by Greelan** [comment]
On the query port, this is what I included in the comments in the original PR (before it was prematurely merged into experimental):

`The template is configured to use a query port but the server does not appear to listen on that port (it only appears to listen on the UDP game port). It appears the server online subsystem has recently been changed from Steam to EOS, which may be the reason.`

The online guides refer to Steam ports but I suspect they are out of date.

**Comment by IceOfWraith** [comment]
I figured you wouldn't have missed that. Lol

**Comment by Greelan** [comment]
@IceOfWraith, see what you think of my own "GitRepo" update stage implementation. Lol.

`git-lfs` needs to be installed.

**Comment by IceOfWraith** [comment]
I hate it and I love it at the same time. I'll give this a try later this week. Lol

**Comment by PhonicUK** [comment]
I've added git-lfs to the base image.

**Review by IceOfWraith — DISMISSED** [review]
This one looks good too.

**Comment by Greelan** [comment]
Config file download path also updated for this template, @IceOfWraith

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
