### PR TITLE
Fortresscraft Evolved

### PR DESCRIPTION
**Pull request by 1473625**
have fun

### CODE REVIEW

**Comment by 1473625** [comment]
i hope its good

**Comment by IceOfWraith** [comment]
Have you tested this template? It seems there are some glaring issues. For instance there is JSON at the top of the kvp file. The Steam download app ID is not the dedicated server one.

**Comment by 1473625** [comment]
no I wanted to create a template for the first time to see if it works
    Am Samstag, 23. Juli 2022 um 21:17:41 MESZ hat IceOfWraith ***@***.***> Folgendes geschrieben:  
 
 


Have you tested this template? It seems there are some glaring issues. For instance there is JSON at the top of the kvp file. The Steam download app ID is not the dedicated server one.

**Comment by Electrofried** [comment]
While it is fantastic that you are learning how templates work, creating a pull request like this generally means you have a working template that you are ready to submit and testing has been done.

You can test a template without doing a pull request simply by loading it in to your own local amp instance. Good luck with your testing and tinkering!

**Comment by 1473625** [comment]
how i can download the finished template for my amp?
    Am Samstag, 23. Juli 2022 um 22:42:43 MESZ hat Electrofried ***@***.***> Folgendes geschrieben:  
 
 


While it is fantastic that you are learning how templates work, creating a pull request like this generally means you have a working template that you are ready to submit and testing has been done.

You can test a template without doing a pull request simply by loading it in to your own local amp instance. Good luck with your testing and tinkering!

**Comment by IceOfWraith** [comment]
I recommend you join the Discord. It is filled with knowledge around this.

You can place the files in this folder and restart ADS:
`ADS01/Plugins/ADSModule/DeploymentTemplates/CubeCoders-AMPTemplates`

The first folder might be a variation of ADS rather than that exact name.

**Pull request closed without merging**
