### PR TITLE
Longvinter: settings updates

### PR DESCRIPTION
**Pull request by Greelan**
This:

- adds a `MultiHome` setting
- adds `CoopPlay` and`CoopSpawn`, which are new settings added by the game devs
- reflects the rename of `ServerTag` to `Tag`, while still catering for legacy configs
- reflects that the default server install now include a default config for Game.ini, so the update stages have been changed to use that

The new `CoopSpawn` setting has been left as a number type for now, for it is not clear what the range of settings are. However, it can probably be made an enum, since it seems to reflect specified locations (`West` etc). Still waiting for info on that.

### CODE REVIEW

**Review by xLeviNx — DISMISSED** [review]
Looks good. closing other pull request. Also tested. Nice work

**Comment by Greelan** [comment]
Thanks. By any chance could you do some testing to work out the values for CoopSpawn? Eg West=0 or whatever. I'm hoping that by creating a server through the game GUI the spawn location names can be correlated with their values in Game.ini. I don't have the game client to test

**Comment by IceOfWraith** [comment]
`lisbonjoker` is the game's dev in AMP's Discord if you want to ask them directly.

**Comment by Greelan** [comment]
Good point. I don't think he is a dev as such, but have reached out to him coz he seems closely involved

**Comment by IceOfWraith** [comment]
Ahh right. Not a dev. :)

**Comment by xLeviNx** [comment]
> Thanks. By any chance could you do some testing to work out the values for CoopSpawn? Eg West=0 or whatever. I'm hoping that by creating a server through the game GUI the spawn location names can be correlated with their values in Game.ini. I don't have the game client to test

I ended up returning the game after testing the multi-home function and testing initial longvinter pull request (did not notice the linux addon since I'm more tuned to manually editing things) lol. Mainly testing it for a discord gameserver query so I would not be able to test :/

**Review by IceOfWraith — DISMISSED** [review]
Everything seems in order.  Good work as always!

**Comment by Greelan** [comment]
Sorry, I'm going to update this to tie the MultiHome setting to $ApplicationIPBinding like I've done on some other recent templates

**Comment by Greelan** [comment]
Will hold off merging for the time being as the changes need generic updates to be working again

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
