### PR TITLE
Add Arma 3 template (draft)

### PR DESCRIPTION
**Pull request by Greelan**
Work-in-progress template to replace existing Arma 3 module, to enable greater flexibility on configuration through AMP. Adding as draft for visibility and feedback

### CODE REVIEW

**Comment by jasperfirecai2** [comment]
Giving your commits some more informational names would help, and don't forget to squash the commit history when no longer a draft

**Comment by Greelan** [comment]
> Giving your commits some more informational names would help, and don't forget to squash the commit history when no longer a draft
As this is a working draft and I am committing changes directly on the GH website as I go (since that is the only way to save changes on the website), there are too many minor tweaks here and there to make commit messages meaningful. And yes I fully intend to squash commit. I was looking more for feedback on the content of the template lol

**Comment by IceOfWraith** [comment]
Related issue: https://github.com/CubeCoders/AMP/issues/584

**Comment by IceOfWraith** [comment]
Related issue: https://github.com/CubeCoders/AMP/issues/562

**Pull request closed without merging**
