### PR TITLE
V-Rising Scheduled Wipes

### PR DESCRIPTION
**Pull request by Psychloor**
Add support for scheduled wipes for v-rising games.
parameter names can be found in: https://github.com/StunlockStudios/vrising-dedicated-server-instructions
which I used

### CODE REVIEW

**Comment by Greelan** [comment]
Thanks for this. Are those two settings in the server's default ServerHostSettings.json file?

Also, no need to have two Any settings for the wipe days - just pick one. I suggest AnyDay.

**Comment by Greelan** [comment]
If they are not the file, the settings won't work

**Comment by Psychloor** [comment]
> If they are not in the file, the settings won't work

Worked when I added them to the serverhostsettings file in savedata folder

**Comment by Psychloor** [comment]
But alright got it

**Comment by Greelan** [comment]
> > If they are not in the file, the settings won't work
> 
> Worked when I added them to the serverhostsettings file in savedata folder

Yeah, because then they are ... in the file. Lol

**Pull request closed without merging**
