### PR TITLE
The Isle (EVRIMA): add settings

### PR DESCRIPTION
**Pull request by Greelan**
- Adds new QueuePort settings
- Adds new Discord setting
- QueryPort retained but does not appear to be used anymore, so endpoint URI removed. Cannot get definitive feedback on The Isle discord as to whether used in any circumstances, so keeping as a configured port for the time being

### CODE REVIEW

**Review by IceOfWraith — COMMENTED** [review]
Nothing seems off here. Good work! (as always)

**Review by IceOfWraith — APPROVED** [review]
Helps if I choose "Approve" instead of "Comment"...

**Comment by Greelan** [comment]
I'm seeing some other issues now with the devs' latest server updates which are quite strange. I will continue to look into that and update this PR once I've got more clarity on that.

**Comment by Greelan** [comment]
@IceOfWraith, now made some further tweaks:

- Fixed the QueueEnabled key as despite the devs saying they would change it from a certain version, they haven't
- The Discord setting causes issues for the server starting at least on Windows, so I am removing it
- LinuxBufferedConsole gives more console output on Linux, but messes with the metrics because AMP monitors `socat` instead. WindowsBufferedConsole stops all console output on Windows, so I have kept the AppCompatibility at None

**Review by IceOfWraith — APPROVED** [review]
You're the best.

**Pull request merged**
