### PR TITLE
Add Minetest

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]
Seems to work as advertised. Annoying it has the issue where you may spawn in blocks though. Lol

**Comment by p0t4t0sandwich** [comment]
Seems to be vanilla behavior, their spawn system doesn't check to see if the location is safe

**Comment by IceOfWraith** [comment]
Yeah, Greelan said you guys got around it. Just annoying. That seems like priority one for a game, to make sure you aren't dead on spawn. Lol

**Comment by Greelan** [comment]
I've asked in their discord whether this is a known issue and if so any fix. Will hold off merging the template for now pending a response, as I can see the AMP discord being flooded with "I can't move / my screen is black" with the current behaviour

**Comment by IceOfWraith** [comment]
If it is known, you might want to take the same approach we discussed for ATS/ETS. Make a required checkbox that the user sets a spawn point on first start.

**Comment by Greelan** [comment]
Still waiting on a response, but found this description of the (alleged) algorithm: https://forum.minetest.net/viewtopic.php?p=418987&sid=690b2549ca07cb07c35c5aba70699383#p418987

**Comment by Greelan** [comment]
Got a response on the Minetest discord, apparently a known glitch. No workaround/fix suggested, except to say that someone had previously developed some server tools to help with it

**Pull request merged**
