### PR TITLE
join and leave regex for conan exiles

### PR DESCRIPTION
**Pull request by rezor92**

### CODE REVIEW

**Comment by rezor92** [comment]
There seems to be a problem with the logs / console. The important logs marked as bold heading are missing from the AMPLOG and console.

**GAMELOG:**
> [2023.01.10-17.48.57:349][657]LogNet: Login request: [69aa3663b7660b0899bf9f5d0cd1809a] userId: [bffb91ce391b6acc7a5cec03064cf85a]
> [2023.01.10-17.48.57:349][657]LogDreamworld:Display: PreLogin: [bffb91ce391b6acc7a5cec03064cf85a]
> [2023.01.10-17.48.57:349][657]ConanSandbox:Display: User [bffb91ce391b6acc7a5cec03064cf85a] logged in from unknown country
> [2023.01.10-17.48.57:349][657]LogOnline:Warning: STEAM: Steam API disabled!
> [2023.01.10-17.48.57:350][657]LogOnline:Display: STEAM: OnlineSubsystemSteam::Shutdown()
> [2023.01.10-17.48.57:350][657]LogNet: Client login from 127.0.0.1, with ping 9999
> [2023.01.10-17.48.57:383][658]LogNet: Client netspeed is 25000
> [2023.01.10-17.48.57:716][668]LogFuncomLiveServices:Display: VerifyIdentity Completed: PlayFabId - [4a0a61a5a369c657026a5a8f0a8c9aac] PlatformId - [85c0270f11b675443aea36cbd97d4adc].
> [2023.01.10-17.48.59:210][713]LogNet: Join request: [a3c0534c608575bc0116c517e1384544]
> [2023.01.10-17.48.59:211][713]LogScriptCore:Warning: Script Msg: CacheAchievements or CacheAchievementDescriptions - Cannot map local player to unique net ID
> [2023.01.10-17.48.59:211][713]Login:Display: [BaseGameMode_C_0] FindPlayerStart returns Translation: X=25439.732 Y=283263.156 Z=-19057.104 Rotation: P=0.000000 Y=-95.786804 R=0.000000 Scale X=1.000 Y=1.000 Z=1.000
> [2023.01.10-17.48.59:218][713]Login:Display: [FunCombat_PlayerController_C_1 None] User [4a0a61a5a369c657026a5a8f0a8c9aac] logged in.
> [2023.01.10-17.48.59:218][713]Login:Display: [BaseGameMode_C_0] BaseGameMode.StartLogin PlayerID: {}
> ### **[2023.01.10-17.48.59:218][713]LogNet: Join succeeded: myusername#12345**
> [2023.01.10-17.48.59:249][715]Login:Display: [FunCombat_PlayerController_C_1 None] UserCharacterList: Loading Character 0
> [2023.01.10-17.48.59:249][715]Login:Display: [FunCombat_PlayerController_C_1 None] Creating ADHOC Player Start Translation: X=25439.732 Y=283263.156 Z=-19057.104 Rotation: P=0.000000 Y=-95.786804 R=0.000000 Scale X=1.000 Y=1.000 Z=1.000
> [2023.01.10-17.48.59:249][715]Login:Display: [FunCombat_PlayerController_C_1 None] PreBeginPlay login completed.
> [2023.01.10-17.48.59:285][716]Login:Display: [FunCombat_PlayerController_C_1 None] Could not find actor with UID: 55. Creating new actor for character.
> [2023.01.10-17.48.59:292][716]ConanSandbox:Display: Character ID 55 has name myusername and guild ID 0.
> [2023.01.10-17.48.59:311][716]ConanSandbox:Warning: AConanPlayerController::Possess - Calling BattlEye::PlayerPossessed(this)
> [2023.01.10-17.48.59:312][716]ConanSandbox:Warning: AConanCharacter::EnableLoadingInvulnerability enabled for BasePlayerChar_C_1
> [2023.01.10-17.48.59:647][726]Network:Warning: Data: FunCombat_PlayerController_C_1 (server) sent 87421.0 bytes per second > 10240 (sample window size: 2.00 seconds)
> [2023.01.10-17.48.59:647][726]Network:Warning: Data: FunCombat_PlayerController_C_1 (server) sent 319.5 parts per second > 80 (sample window size: 2.00 seconds)
> [2023.01.10-17.49.01:335][777]GUI:Display: C:\B\tech_exiles\code\UE4\Source\ConanSandbox\Character\ConanPlayerController.cpp(8469): AConanPlayerController::BlockOnStreamingClient_Implementation: SetTeleportState(2), TeleportState=0
> [2023.01.10-17.49.03:323][837]Streaming:Display: Waiting for streaming completed (teleport, unload)
> [2023.01.10-17.49.03:323][837]LogEngine: BlockTillLevelStreamingCompleted: 3
> [2023.01.10-17.49.03:355][838]Streaming:Display: Waiting for streaming completed (teleport, load)
> [2023.01.10-17.49.03:355][838]LogEngine: BlockTillLevelStreamingCompleted: 4
> [2023.01.10-17.49.03:455][841]Streaming:Display: Waiting for streaming completed (teleport): Done.
> [2023.01.10-17.49.03:455][841]GUI:Display: C:\B\tech_exiles\code\UE4\Source\ConanSandbox\Character\ConanPlayerController.cpp(7526): AConanPlayerController::TeleportTick: SetTeleportState(0), TeleportState=2
> [2023.01.10-17.49.06:443][931]ConanSandbox:Warning: AConanCharacter::DisableLoadingInvulnerability disabled for BasePlayerChar_C_1
> [2023.01.10-17.49.15:358][200]LogServerStats: Status report. Uptime=240 Mem=11554263040:34137300992:4023943168:4023943168 CPU=0.148986:2.979722 Players=1 FPS=22.16:33.20:115.16 NPC_AILOD=1:0:0:5408 B_AILOD=0:0:0:0 P_AILOD=0:0:0:38
> [2023.01.10-17.49.55:164][397]LogNet: UChannel::ReceivedSequencedBunch: Bunch.bClose == true. ChIndex == 0. Calling ConditionalCleanUp.
> ### **[2023.01.10-17.49.55:164][397]LogNet: Player disconnected: myusername#12345**
> [2023.01.10-17.49.55:164][397]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 127.0.0.1:59469, Player name: myusername#12345
> [2023.01.10-17.50.15:331][  5]LogServerStats: Status report. Uptime=300 Mem=10986491904:34137300992:4521164800:4522045440 CPU=0.294978:5.899552 Players=0 FPS=29.66:33.23:148.89 NPC_AILOD=0:0:0:6639 B_AILOD=0:0:0:0 P_AILOD=0:0:0:38
> [2023.01.10-17.50.46:821][952]LogRcon:Warning: Closing connection with PeerAddr: 127.0.0.1:53954 
> [2023.01.10-17.50.46:822][952]LogRcon:Display: Rcon Client PeerAddr: 127.0.0.1:53954 disconnected.

**AMPLOG:**
> LogDreamworld:Display: PreLogin: [bffb91ce391b6acc7a5cec03064cf85a]
> ConanSandbox:Display: User [bffb91ce391b6acc7a5cec03064cf85a] logged in from unknown country
> LogOnline:Warning: STEAM: Steam API disabled!
> LogOnline:Display: STEAM: OnlineSubsystemSteam::Shutdown()
> LogFuncomLiveServices:Display: VerifyIdentity Completed: PlayFabId - [4a0a61a5a369c657026a5a8f0a8c9aac] PlatformId - [85c0270f11b675443aea36cbd97d4adc].
> LogScriptCore:Warning: Script Msg: CacheAchievements or CacheAchievementDescriptions - Cannot map local player to unique net ID
> Login:Display: [BaseGameMode_C_0] FindPlayerStart returns Translation: X=-47618.094 Y=274800.438 Z=-20549.344 Rotation: P=0.000000 Y=-95.786804 R=0.000000 Scale X=1.000 Y=1.000 Z=1.000
> Login:Display: [FunCombat_PlayerController_C_0 None] User [4a0a61a5a369c657026a5a8f0a8c9aac] logged in.
> Login:Display: [BaseGameMode_C_0] BaseGameMode.StartLogin PlayerID: {}
> Login:Display: [FunCombat_PlayerController_C_0 None] UserCharacterList: Loading Character 0
> Login:Display: [FunCombat_PlayerController_C_0 None] Creating ADHOC Player Start Translation: X=-47618.094 Y=274800.438 Z=-20549.344 Rotation: P=0.000000 Y=-95.786804 R=0.000000 Scale X=1.000 Y=1.000 Z=1.000
> Login:Display: [FunCombat_PlayerController_C_0 None] PreBeginPlay login completed.
> ConanSandbox:Warning: AConanPlayerController::Possess - Calling BattlEye::PlayerPossessed(this)
> ConanSandbox:Warning: AConanCharacter::EnableLoadingInvulnerability enabled for BasePlayerChar_C_0
> GUI:Display: C:\B\tech_exiles\code\UE4\Source\ConanSandbox\Character\ConanPlayerController.cpp(8469): AConanPlayerController::BlockOnStreamingClient_Implementation: SetTeleportState(2), TeleportState=0
> Network:Warning: Data: FunCombat_PlayerController_C_0 (server) sent 87708.5 bytes per second > 10240 (sample window size: 2.00 seconds)
> Network:Warning: Data: FunCombat_PlayerController_C_0 (server) sent 329.5 parts per second > 80 (sample window size: 2.00 seconds)
> Streaming:Display: Waiting for streaming completed (teleport, unload)
> Streaming:Display: Waiting for streaming completed (teleport, load)
> Streaming:Display: Waiting for streaming completed (teleport): Done.
> GUI:Display: C:\B\tech_exiles\code\UE4\Source\ConanSandbox\Character\ConanPlayerController.cpp(7526): AConanPlayerController::TeleportTick: SetTeleportState(0), TeleportState=2
> ConanSandbox:Warning: AConanCharacter::DisableLoadingInvulnerability disabled for BasePlayerChar_C_0
> SpawnTable:Error: Data: USpawnTableLibrary::SpawnNPCFromWeightedTable - could not find weighted table with id: we
> LogOutputDevice:Display: Bug report upload completed with result code 200, took 0.193 seconds.
> SpawnTable:Error: Data: USpawnTableLibrary::SpawnNPC - could not find SpawnTable with ID: GorillaSilverback
> SpawnTable:Error: Data: USpawnTableLibrary::SpawnNPC - could not find SpawnTable with ID: GorillaSilverback

**Comment by Greelan** [comment]
No utility having the regex if the console doesn't show the relevant log lines. 

Have you tried to increase console logging by replacing `-log` in the command line args with `-stdout` or even `-stdout -FullStdOutLogOutput`? That has helped on some other UE4 servers.

**Comment by rezor92** [comment]
Hi Greelan, thanks for your answer. I think I was not precise enough. The lines which i try to regex are written the server log files and are shown in the console window of the server itself. Sadly they are missing from the amp instance log files and are not visible in the web console of amp. It seems like the are magically filtered out by amp. The attached image shows such log entry in the server console which was started with this command:

ConanSandboxServer-Win64-Test.exe /Game/Maps/ConanSandbox/ConanSandbox -log -Port=7777 -QueryPort=27015 -RconPort=25575 -RconEnabled=1 -RconPassword="*****" -MaxPlayers=40 -ServerName="Conan Exiles Server - Powered by AMP"

image

**Comment by Greelan** [comment]
No, I did understand. Ultimately if the log does not appear in AMP's console, the regex can't match.

**Pull request closed without merging**
