### PR TITLE
Counter-Strike 2: add workshop settings and switch to anonymous download

### PR DESCRIPTION
**Pull request by Greelan**

### CODE REVIEW

**Review by IceOfWraith — APPROVED** [review]

**Comment by xLeviNx** [comment]
Looks good 

Requesting to add feature: sv_workshop_allow_other_maps true/false 
`When` hosting a workshop collection, users can play other workshop map on this server when it is empty and then mapcycle into this server collection.``

**Review by IceOfWraith — APPROVED** [review]

**Comment by Greelan** [comment]
> Looks good
> 
> Requesting to add feature:
> 
> > sv_workshop_allow_other_maps true/false
> 
> `When hosting a workshop collection, users can play other workshop map on this server when it is empty and then mapcycle into this server collection.`

You sure?

`help: no cvar or command named sv_workshop_allow_other_map`

**Comment by Greelan** [comment]
Ah, oops, typo lol. Now added

**Review by IceOfWraith — APPROVED** [review]

**Comment by xLeviNx** [comment]
> > Looks good
> > Requesting to add feature:
> > > sv_workshop_allow_other_maps true/false
> > 
> > 
> > `When hosting a workshop collection, users can play other workshop map on this server when it is empty and then mapcycle into this server collection.`
> 
> You sure?
> 
> `help: no cvar or command named sv_workshop_allow_other_map`

sv_workshop_allow_other_maps (forgot the s)

**Comment by Greelan** [comment]
Yeah, already noted I had a typo

**Pull request merged**
