### PR TITLE
Core Keeper Generic Template

### PR DESCRIPTION
**Pull request by Shinynecrid**
Add support for core keeper generic module for AMP.

Known Issues:
Windows - no (manual) saving have to wait for auto save. there is no way to interact with a console/or issue commands to the server.
Linux - need to setup xvfb

### CODE REVIEW

**Comment by Greelan** [comment]
As per my PR against @Shinynecrid's repo, suggested updates included here: https://github.com/Greelan/AMPTemplates/tree/core-keeper

**Comment by Greelan** [comment]
Further changes to the kvp to essentially remove the port allocation: https://github.com/Greelan/AMPTemplates/blob/core-keeper/core-keeper.kvp

**Comment by Greelan** [comment]
Yeah, the 100 just reflects the defaults that are in the readme.txt and ServerConfig.json. People on Discord have noted the discrepancy but who knows?

**Comment by IceOfWraith** [comment]
Gotcha! That makes sense. I figured it wasn't a random number you chose. Lol

**Comment by Greelan** [comment]
This is really early access stuff, both the game and even more so the server, so will no doubt be developed further.

**Pull request merged**
