### PR TITLE
Add Carrier Command 2

### PR DESCRIPTION
**Pull request by Greelan**
Adds Carrier Command 2 dedicated server (re-adding after the previous PR was prematurely merged into experimental).

- Configured for both Windows and Linux. Uses Wine on Linux.
- Requires the game to be purchased on Steam.
- Uses four sequential ports (default 25565-25568 UDP). AMP cannot yet achieve this automatically.
- Settings are based on the official docs and feedback from other users on their discussion forum.
- Config download path to be updated before merging.

I have tested with the game client myself and have had no issues.

### CODE REVIEW

**Comment by IceOfWraith** [comment]
Adding this for tracking: https://github.com/CubeCoders/AMP/issues/562

**Review by IceOfWraith — DISMISSED** [review]
I don't own the game, so I can't test connecting. The config loads and I don't see any errors after reviewing it. This looks good to merge.

**Comment by Greelan** [comment]
@IceOfWraith, pls review again as I needed to update the GH repo for the config download before merging, and now it needs another review...

**Review by IceOfWraith — APPROVED** [review]
Done.

**Pull request merged**
