### PR TITLE
Geyser: overhaul of template

### PR DESCRIPTION
**Pull request by Greelan**
Updates the Geyser template for current AMP functionality, including:
- fixing ports
- updating regex
- adding Java settings
- adding Docker support

### CODE REVIEW

**Comment by IceOfWraith** [comment]
Related: https://github.com/CubeCoders/AMP/issues/682

**Comment by Greelan** [comment]
Lol, that issue about %PATH% not being used is correct. So how did the existing template get merged? 🤔

**Comment by PhonicUK** [comment]
```App.ExecutableWin=$PATH/java``` - missing .exe there :)

**Comment by Greelan** [comment]
In the PR, yes, but I did test an instance with the extension and it still did not work

**Comment by Greelan** [comment]
`[11:05:56] [Generic:admin Info]   : Specified executable 'C:\AMPDatastore\Instances\Geyser01\geyser\$PATH\java.exe does not exist. Updating application...` 👀
@PhonicUK

**Comment by PhonicUK** [comment]
Should be good in the 2.4 beta in Nightly?

**Review by IceOfWraith — APPROVED** [review]
Nice workaround. Ice approves.

**Pull request merged**
