### PR TITLE
Re-Write of Squad [Draft]

### PR DESCRIPTION
**Pull request by Shinynecrid**
Re-Write squad generic module, add web settings. Add Skeleton for Vote Config

### CODE REVIEW

**Comment by PhonicUK** [comment]
Tests pending if someone else can validate it?

**Comment by IceOfWraith** [comment]
I'm not sure why this one is in testing. It needs regex and I believe maybe something else. I think it was removed from draft too soon.

**Comment by Shinynecrid** [comment]
i noticed after the fact don't merge this yet.

**Comment by Shinynecrid** [comment]
nvm. i figured out how to re-mark as draft.

**Comment by Shinynecrid** [comment]
Module Largely in a good state. This Template is awaiting feature https://github.com/CubeCoders/AMP/issues/573 in order to be able to set the server password through AMP's Web Settings. but other than that. This module should be ready for testing.

**Review by IceOfWraith — CHANGES_REQUESTED** [review]
Unsure if one setting needs corrected:
Server Message Interval
Maximum Allowed difference in player count between teams. This takes into account the team the player leaves and the team the player joins

Also, recommend putting suffixes on inputs that it could help clarify (players, sec, etc.).

Otherwise, this looks good!

**Review by IceOfWraith — APPROVED** [review]
It works as intended and the changes look good!

**Pull request merged**
