### PR TITLE
Add NEBULOUS: Fleet Command

### PR DESCRIPTION
**Pull request by Greelan**
Adds NEBULOUS: Fleet Command Dedicated Server

### CODE REVIEW

**Review by Shinynecrid — DISMISSED** [review]
Tested! Made several servers. Console works, Modding Works, Scenario's Work. Will comment back if Issues are found, but overall solid and funcional 👍

**Comment by Greelan** [comment]
@Shinynecrid thanks for testing. You may not know, but can additional scenarios be added by mods? I've listed as an enum those that server listed but I wonder whether I need to cater for custom ones as well.

**Comment by Shinynecrid** [comment]
@Greelan I'm not sure, but let me see what I can find out.

**Comment by Greelan** [comment]
I asked in their discord. A mod developer there said that mods can add scenario types. So I will adjust the template

**Review by Shinynecrid — APPROVED** [review]
Server still seems to function and operate as intended. Will report back if anything isn't. Wasn't able to use the change of "Writable Console", but still can change stuff in-game so it's probably ok.

**Comment by Greelan** [comment]
Oh yeah, the change to writeable console has no impact - usual story with AMP's console. But it has no negative effects either. And it's there in case AMP's console handling is ever improved. 

And ofc the use of sessionid to track players is still broken in AMP.

**Comment by Shinynecrid** [comment]
No worries on the console. I remember this from back in the day, and I figured it was fixed by now, but anyway solid release, and thank you Greelan.

**Comment by Greelan** [comment]
@Shinynecrid can you please approve this again and I will merge it

**Review by IceOfWraith — APPROVED** [review]

**Pull request merged**
